cloud/aws/setup.sh
pkg/config/testdata/agent/auth_token_overwrite.golden.yaml
pkg/config/testdata/agent/basic.golden.yaml
pkg/config/testdata/agent/debug_overwrite.golden.yaml
pkg/config/testdata/agent/https_overwrite.golden.yaml
pkg/config/testdata/agent/prometheus_overwrite.golden.yaml
pkg/config/testdata/agent/scylla_overwrite.golden.yaml
pkg/rclone/options.go
pkg/service/backup/worker_upload.go

rclone: disable traversing destination directories by default

---

docs/source/backup/index.rst
docs/source/backup/specification.rst

docs: backup, add specification (#2800)

---

pkg/service/scheduler/service.go
pkg/service/scheduler/service_integration_test.go

service/scheduler: make suspend and resume idempotent (#2849)

---

docs/source/backup/examples.rst

docs: backup, Add section about archiving keyspace [#2918]

---

pkg/command/progress/cmd.go
pkg/managerclient/model.go
pkg/restapi/services.go
pkg/restapi/task.go
pkg/service/scheduler/service.go
pkg/service/scheduler/service_integration_test.go

sctool: progress add support for ~n syntax to get the n-th last run

---

dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Also unifing dockerfile package location so we can run docker build
command from dist folder

Update dockerfile with missing packages

---

pkg/cmd/scylla-manager/server.go
pkg/command/backup/cmd.go
pkg/command/backup/update-res.yaml
pkg/command/info/cmd.go
pkg/command/info/res.yaml
pkg/command/legacy/task/taskprogress/cmd.go
pkg/command/progress/cmd.go
pkg/command/repair/cmd.go
pkg/command/repair/update-res.yaml
pkg/command/start/cmd.go
pkg/command/start/res.yaml
pkg/command/stop/cmd.go
pkg/command/stop/res.yaml
pkg/managerclient/client.go
pkg/managerclient/tasks.go
pkg/managerclient/utils.go
pkg/managerclient/utils_test.go
pkg/restapi/task.go
pkg/service/scheduler/model.go
pkg/service/scheduler/service_integration_test.go
pkg/service/scheduler/service_list.go
swagger/gen/scylla-manager/client/operations/get_cluster_cluster_id_tasks_parameters.go
swagger/scylla-manager.json

sctool make task ID optional if there is a single task of a given type

---

pkg/cmd/agent/nodeinfo.go
pkg/cmd/agent/nodeinfo_linux.go
pkg/cmd/agent/nodeinfo_unix.go
pkg/util/cpuset/cpuset.go
pkg/util/cpuset/cpuset_linux.go
pkg/util/cpuset/cpuset_linux_test.go
pkg/util/cpuset/cpuset_test.go
pkg/util/cpuset/cpuset_unix.go

Some comments seem to point out that it has been working at some point in time.

Bring back MacOS agent

---

pkg/cmd/sctool/root.go
pkg/managerclient/client.go

Add more flexibility in client configuration.
Fixes #2949

managerclient: add options in NewClient

---

pkg/command/info/cmd.go

command/info: render full command args

---

pkg/service/repair/service.go

service/repair: worker, add trace_id to worker logs

---

pkg/command/flag/flag.go
pkg/command/flag/task.go
pkg/command/flag/task.yaml
pkg/command/flag/type.go
pkg/service/scheduler/details.go
pkg/service/scheduler/listener.go
pkg/service/scheduler/model.go
pkg/service/scheduler/service.go
pkg/service/scheduler/service_integration_test.go
schema/v3.0.0.cql
swagger/gen/scylla-manager/models/schedule.go
swagger/scylla-manager.json

export retry wait

---

pkg/command/repair/cmd.go

command/repair: add missing parameters handling

---

pkg/command/suspend/cmd.go
pkg/command/suspend/res.yaml
pkg/command/suspend/update-res.yaml
pkg/managerclient/tasks.go
pkg/service/scheduler/model.go
pkg/service/scheduler/model_test.go
pkg/service/scheduler/service.go
pkg/service/scheduler/service_integration_test.go
pkg/service/scheduler/service_list.go
pkg/service/scheduler/service_suspend.go

schedule suspend

---

dist/deb/scylla-manager-agent.preinst
dist/deb/scylla-manager-server.preinst
dist/rpm/scylla-manager-agent.preinst
dist/rpm/scylla-manager-server.preinst

dist: useradd replace -d flag with -b

---

dist/deb/scylla-manager-agent.preinst
dist/deb/scylla-manager-server.preinst
dist/rpm/scylla-manager-agent.preinst
dist/rpm/scylla-manager-server.preinst
pkg/restapi/cluster.go
pkg/scyllaclient/client.go
pkg/scyllaclient/client_agent_test.go
pkg/scyllaclient/client_rclone.go
pkg/scyllaclient/client_rclone_test.go
pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/config.go
pkg/scyllaclient/retry.go
pkg/scyllaclient/retry_test.go
pkg/scyllaclient/scyllaclienttest/client.go
pkg/scyllaclient/status.go
pkg/scyllaclient/status_test.go

Cherry-pick of commits to 2.6 branch.

branch 2.6 update

---

docs/source/restore/index.rst

Fix #3021
This PR improve and add example to teh var,yaml file used in restore

Add example to var.yaml used in restore

---

pkg/config/agent/agent.go
pkg/config/agent/agent_test.go
pkg/config/agent/testdata/structs_empty.golden.yaml
pkg/config/agent/testdata/structs_empty.input.yaml
pkg/config/server/server.go
pkg/scheduler/trigger/cron_test.go
pkg/util/cfgutil/cfgutil.go
pkg/util/cfgutil/cfgutil_test.go

config/agent: use s3 defaults when config is empty

---

docs/source/restore/index.rst

A follow up to https://github.com/scylladb/scylla-docs/issues/3010

docs: Add a prerequisite and a note to the restore procedure

---

docs/source/_templates/command.tmpl
docs/source/sctool/global-flags-and-variables.rst

Closes https://github.com/scylladb/scylla-manager/issues/3007
Preview:

docs: collapse inherited options

---

pkg/service/backup/purger.go
pkg/service/backup/purger_test.go

service/backup: use timeutc for purger

---

ansible/restore/restore.yaml

A restore.yaml Ansible playbook is completely broken.
This series brings it back to life.
See more info in patches descriptions.

Restore from sm backup rework

---

Makefile
pkg/metrics/scheduler.go
pkg/metrics/scheduler_test.go
pkg/metrics/testdata/SchedulerMetrics/BeginEndRun.golden.txt
pkg/service/scheduler/service.go

metrics: add last success

---

pkg/service/scheduler/service.go

service/scheduler: remove deleted task from resolver

---

docs/source/docker/index.rst

docs: document MinIO bucket creation for docker

---

go.mod
go.sum
vendor/github.com/rclone/rclone/fs/operations/operations.go
vendor/modules.txt

- Latest patched version of rclone reduces file copy logs to DEBUG level
fixes #3041

rclone: update rclone dependency to reduce logs

---

pkg/command/cluster/clusteradd/cmd.go
pkg/scyllaclient/client_rclone.go

Update comment and sctool example

---

docs/source/docker/index.rst
docs/source/sctool/partials/sctool.yaml
docs/source/sctool/partials/sctool_status.yaml
go.mod
go.sum
pkg/command/cluster/clusteradd/cmd.go
pkg/command/status/res.yaml
pkg/managerclient/model.go
pkg/schema/table/table.go
pkg/scyllaclient/client_rclone.go
pkg/service/backup/list.go
pkg/service/repair/model.go
pkg/service/repair/service.go
pkg/service/scheduler/service.go
schema/v3.0.0.cql
swagger/gen/scylla-manager/models/repair_progress.go
swagger/scylla-manager.json
vendor/github.com/rclone/rclone/fs/operations/operations.go
vendor/modules.txt

Cherry-pick recent commits to 3.0

3.0 cherry pick

---

pkg/scyllaclient/retry.go

scyllaclient: fix return of nil body on err != nil

---

pkg/service/backup/backupspec/location.go

service/backup: allow path in backup location

---

pkg/scyllaclient/config.go

scyllaclient: increase default timeout to 30s

---

docs/source/_templates/command.tmpl

Closes https://github.com/scylladb/scylla-manager/issues/3103
Adds anchors to options.

docs: add anchor to options

---

pkg/service/backup/backupspec/location.go

reverting for #3086. Needs to be improved and go into 3.1.

Revert 3086 2.6

---

pkg/service/backup/backupspec/location.go

reverting for #3086. Needs to be improved and go into 3.1.

Revert 3086

---

pkg/service/backup/backupspec/location.go

reverting for #3086. Needs to be improved and go into 3.1.

Revert 3086 3.0

---

pkg/scyllaclient/client_rclone.go
pkg/service/backup/backupspec/manifest.go
pkg/service/backup/purger.go
pkg/util/jsonutil/seek.go
pkg/util/jsonutil/seek_test.go

service/backup: iteratively load manifest index

---

pkg/scyllaclient/client_scylla.go

scyllaclient: check metric values for nils

---

pkg/rclone/operations/errors.go
pkg/rclone/operations/errors_test.go
pkg/rclone/operations/operations.go
pkg/rclone/rcserver/rcserver.go

rclone: retryable check location

---

dist/systemd/scylla-manager.service
pkg/scyllaclient/client.go
pkg/service/backup/purger.go

limit tables processed in parallel

---

pkg/service/backup/service_backup_integration_test.go
pkg/service/healthcheck/service_integration_test.go
pkg/service/repair/range.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go

Patch to Manager 3.0 containing single optimization https://github.com/scylladb/scylla-manager/issues/3128
---

Branch 3.0 patch

---

Makefile
pkg/service/backup/service_backup_integration_test.go
pkg/service/cluster/service_integration_test.go
pkg/service/healthcheck/service_integration_test.go
pkg/service/repair/range.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go

Patch to Manager 2.6 containing single optimization https://github.com/scylladb/scylla-manager/issues/3128
---

Branch 2.6 patch

---

pkg/service/repair/service_repair_integration_test.go

service/repair: fix for repair restart fixes failed ranges test case

---

.golangci.yml
pkg/cmd/agent/router.go

Prometheus_address fix backport

---

pkg/config/server/server.go
pkg/config/server/server_test.go
pkg/config/server/testdata/scylla-manager.yaml
pkg/service/healthcheck/config.go
pkg/service/healthcheck/service.go

service/healtcheck: use MaxTimeout instead of RelativeTimeout

---

dist/Makefile

update master dev version number from 3.0-dev to 3.1-dev
closes: https://github.com/scylladb/scylla-pkg/issues/3209

update master version to 3.1-dev

---

pkg/service/backup/service_backup_restore_integration_test.go

Fixes failing integration-test from recent merge
---

integration-test: cqlping.Ping to cqlping.NativeCQLPing

---

dist/.goreleaser.yaml
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Reverts scylladb/scylla-manager#3281

Revert ".goreleaser: add support for arm based docker image"

---

pkg/managerclient/model.go
pkg/managerclient/utils.go
pkg/service/backup/model.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
swagger/gen/scylla-manager/models/backup_target.go
swagger/scylla-manager.json

Merged retention and retention days into retention policy

---

pkg/cmd/scylla-manager/server.go
pkg/service/backup/service.go
pkg/service/backup/validation.go
pkg/service/scheduler/service_integration_test.go

Backup ignoring retention fix

---

docs/source/swagger/index.rst

It's not a file, it's a website
Link to the upstream project.
Fixed minor items in the document itself.

Update Swagger UI doc

---

pkg/service/backup/restore_worker_data.go

Restoring tables with no SSTables caused SM to block.
This PR fixes that.
Fixes #3326

Skip restoring tables with no remaining SSTables

---

dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

dist: dockerfile update

---

pkg/service/backup/service_backup_integration_test.go

Follow-up to the previous commit on master
---

integration-tests: fix failed build of service_backup_integration_test

---

pkg/config/agent/testdata/auth_token_overwrite.golden.yaml
pkg/config/agent/testdata/basic.golden.yaml
pkg/config/agent/testdata/debug_overwrite.golden.yaml
pkg/config/agent/testdata/https_overwrite.golden.yaml
pkg/config/agent/testdata/prometheus_overwrite.golden.yaml
pkg/config/agent/testdata/scylla_overwrite.golden.yaml
pkg/config/agent/testdata/structs_empty.golden.yaml
pkg/rclone/options.go
pkg/scyllaclient/client_rclone.go
pkg/scyllaclient/client_rclone_test.go

rclone: compare files basing on checksum

---

docs/source/restore/download-files-command.rst

download-files: update documentation with suggestion to extend fd soft limit

---

dist/etc/scylla-manager.yaml

healthcheck: config file update / removed relative_timeout and probes

---

pkg/service/backup/restore.go
pkg/service/backup/service_backup_restore_integration_test.go

restore: skip mv and si restoration

---

Makefile
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst
docs/source/sctool/partials/sctool.yaml
docs/source/sctool/partials/sctool_backup.yaml
docs/source/sctool/partials/sctool_backup_list.yaml
docs/source/sctool/partials/sctool_backup_update.yaml
docs/source/sctool/partials/sctool_backup_validate.yaml
docs/source/sctool/partials/sctool_backup_validate_update.yaml
docs/source/sctool/partials/sctool_progress.yaml
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
docs/source/sctool/partials/sctool_suspend.yaml
docs/source/sctool/partials/sctool_suspend_update.yaml

Update restore documentation

---

pkg/service/backup/restore.go
pkg/service/backup/restore_model.go
pkg/service/backup/restore_worker_tables.go
pkg/service/backup/service_backup_restore_integration_test.go

This PR removes unnecessary clutter from restore tests.

Refactor restore tests

---

docs/source/conf.py

docs: update to 3.1

---

pkg/service/backup/restore_worker.go
pkg/service/backup/restore_worker_tables.go

This PR adds retry mechanism to disabling table's gc_grace_seconds.
Fixes #3379

restore: add retry to disabling table ggs

---

docs/source/sctool/restore.rst

docs: fix sctool restore page

---

docs/source/sctool/partials/sctool_progress.yaml
pkg/command/legacy/task/taskprogress/res.yaml
pkg/command/progress/res.yaml

docs: fix missing dash for run flag in progress cmd description

---

pkg/service/repair/service_repair_integration_test.go
pkg/testutils/hrt.go

This PR adds repair test which checks if there is at most one repair executed on each host.
This test does not pass in current repair implementation, but it is a good point of reference for repair procedure refactor.

Repair: test single repair on single host

---

docs/source/backup/specification.rst

This PR adds missing information about backup sstable versioning.
Fixes #3432

Document sstable versioning

---

docs/source/restore/restore-schema.rst

docs: update restore-schema prerequisite

---

docs/source/upgrade/index.rst

docs: update list of supported platforms

---

pkg/auth/auth_test.go
pkg/cmd/sctool/baseurl_test.go
pkg/cmd/sctool/sctool_test.go
pkg/util/cfgutil/cfgutil_test.go
pkg/util/cpuset/cpuset_linux_test.go
pkg/util/retry/retry_test.go
pkg/util/slice/contains_test.go
pkg/util/uuid/sort_test.go

I noticed that some of the tests are running sequentially without reason.

fix(tests): make rest of the test parallel

---

docs/source/backup/setup-amazon-s3.rst
docs/source/backup/setup-azure-blobstorage.rst
docs/source/backup/setup-s3-compatible-storage.rst

docs: req for service restart after config change

---

dist/etc/scylla-manager.yaml
pkg/config/server/server_test.go
pkg/config/server/testdata/scylla-manager.yaml
pkg/service/backup/config.go

backup: default age_max to 24h

---

.github/actions/test-setup/action.yml
.github/workflows/go.yml
.github/workflows/integration-tests.yaml
Makefile
pkg/service/backup/service_backup_restore_integration_test.go
testing/.env
testing/Makefile

This PR changes gh actions workflow so that it runs against many Scylla versions.
Fixes #3471

Use many Scylla versions in gh actions

---

pkg/service/backup/service_backup_integration_test.go

Fix TestBackupRestoreIntegration

---

docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
pkg/command/repair/res.yaml

Replacement of https://github.com/scylladb/scylla-manager/pull/3508
Fixes #3505 
---

doc: fix the description of repair parallel

---

CODEOWNERS

repo: add CODEOWNERS

---

docs/source/restore/restore-tables.rst
docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/res.yaml

This PR is a follow-up to restore changes introduced in SM 3.2.
Related #3479
Fixes #3489
Fixes #3488

Restore docs: updated restore tables documentation

---

pkg/managerclient/client.go

fix(repair): update params of disabled tasks using its names only

---

pkg/scyllaclient/client_scylla.go
pkg/service/backup/service_backup_restore_integration_test.go
pkg/service/repair/service_repair_integration_test.go
pkg/testutils/db/db.go

This PR adds test checking:
- repair pause and resume
- repair completeness (all token ranges are repaired)
And it also improves the test checking:
- repair order 
- repair table by table

Improve repair tests

---

docs/source/conf.py
docs/source/repair/index.rst
docs/source/repair/repair-faster.rst
docs/source/repair/repair-slower.rst
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
pkg/command/repair/res.yaml

This PR contains missing documentation changes from SM 3.2 repair refactor.

Properly document repair changes

---

pkg/service/repair/plan.go
pkg/service/repair/preference.go
pkg/service/repair/preference_test.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go

Repair: make repair system keyspace first more robust

---

pkg/service/backup/service_backup_integration_test.go

Fix flaky TestBackupResumeIntegration/resume_after_stop

---

pkg/scyllaclient/client_ping.go
pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/runner.go
pkg/service/healthcheck/service.go

Healthcheck: don't report -1 in ping metrics when agent is down

---

docs/source/repair/examples.rst
docs/source/sctool/index.rst
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_control.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
docs/source/sctool/partials/sctool_tasks.yaml
pkg/command/repair/repaircontrol/res.yaml
pkg/command/repair/res.yaml
pkg/command/repair/update-res.yaml
pkg/command/tasks/res.yaml

Update repair oriented examples

---

pkg/metrics/scheduler.go
pkg/service/scheduler/service_suspend.go

feat(scheduler): add suspended metric (#3567)

---

docs/source/repair/index.rst
docs/source/sctool/partials/sctool_progress.yaml
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_control.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
pkg/command/progress/res.yaml
pkg/command/repair/repaircontrol/res.yaml
pkg/command/repair/res.yaml
pkg/managerclient/utils.go
pkg/managerclient/utils_test.go

Fixes #3578
Fixes #3581
Fixes #3576

Expand repair docs

---

pkg/service/repair/plan.go
pkg/service/repair/service_repair_integration_test.go

Repair: fix small table optimization on big tables

---

pkg/service/repair/generator.go
pkg/service/repair/plan.go
pkg/service/repair/service_repair_integration_test.go

3.2.2 hot patch release
Fix for small-tables optimization regression.
---

Release 3.2.2

---

docs/source/repair/examples.rst
pkg/managerclient/utils.go
pkg/schema/table/table.go
pkg/service/repair/model.go
pkg/service/repair/progress.go
pkg/service/repair/progress_integration_test.go
pkg/service/repair/service.go
pkg/service/repair/service_integration_test.go
pkg/service/repair/service_repair_integration_test.go
schema/v3.2.2.cql

[Approach description](https://github.com/scylladb/scylla-manager/issues/3580#issuecomment-1733600650)
Fixes #3580

Respect repair control on retry

---

docs/source/restore/compatibility-matrix.rst

Docs: add 3.2 restore compatibility

---

dist/.goreleaser.yaml
dist/Makefile
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

https://github.com/scylladb/scylla-manager/pull/3596
https://github.com/scylladb/scylla-manager/issues/3278
---

Release 3.2.3 update

---

.github/pull_request_template.md

gh: update PR footer

---

pkg/scyllaclient/client_rclone.go

Scyllaclient: increase t/o of listing versioned files

---

pkg/managerclient/model.go
pkg/managerclient/utils.go

Takes care of bugs (points 2 and 3) of #3621.

Display finished repair parallel and intensity

---

docs/source/backup/setup-s3-compatible-storage.rst

Update s3 compatible storage description with information about custom CAs

---

pkg/scyllaclient/client_scylla.go
pkg/service/repair/plan.go

Allow scheduling and running repair on a single node cluster

---

Makefile
pkg/rclone/aws.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/stage.go
pkg/service/backup/worker.go
pkg/service/backup/worker_index.go
pkg/service/backup/worker_manifest.go
pkg/service/backup/worker_purge.go
pkg/service/backup/worker_schema.go
pkg/service/backup/worker_snapshot.go
pkg/service/backup/worker_upload.go

Includes:
- https://github.com/scylladb/scylla-manager/pull/3731
- https://github.com/scylladb/scylla-manager/pull/3735
---

Update release 3.2.6

---

dist/Makefile

release: prepare for 3.2.6

---

pkg/cmd/agent/download_files.go

Load index into memory in download-files

---

pkg/service/cluster/service.go

2226fb42630e931d577b01bba615d0ad5fffb4d0
---

Release 3.2.7 part#3

---

docs/source/restore/index.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst

Improve restore schema topology requirement

---

pkg/scyllaclient/ring_describer.go
pkg/service/repair/generator.go
pkg/service/repair/progress.go
pkg/service/repair/progress_integration_test.go

Disable tablet migration on repair

---

pkg/cmd/scylla-manager/root.go
pkg/cmd/scylla-manager/server.go
pkg/service/configcache/service.go
pkg/service/configcache/service_test.go

Start config cache service + panic recovery

---

pkg/cmd/scylla-manager/server.go
pkg/service/healthcheck/service.go
pkg/service/healthcheck/service_integration_test.go

Fixes https://github.com/scylladb/scylla-manager/issues/3799
---

Redirect cache hits in healthcheck to config cache service

---

pkg/service/configcache/nodeconfig.go
pkg/service/configcache/service.go
pkg/service/configcache/tlsconfig.go
pkg/service/healthcheck/service.go

Fixes https://github.com/scylladb/scylla-manager/issues/3815
---

Store CQL and Alternator TLS config explicitly outside of map

---

pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/worker.go

Make gh actions tests green

---

pkg/service/healthcheck/metrics_test.go
pkg/service/healthcheck/runner.go
pkg/service/healthcheck/service.go

fix(healthcheck): log ping errors

---

docs/source/sctool/partials/sctool_backup.yaml
docs/source/sctool/partials/sctool_backup_delete.yaml
docs/source/sctool/partials/sctool_backup_list.yaml
docs/source/sctool/partials/sctool_backup_update.yaml
docs/source/sctool/partials/sctool_backup_validate.yaml
docs/source/sctool/partials/sctool_backup_validate_update.yaml
pkg/command/flag/usage.yaml

Docs: Rename 'name' to 'bucket' in sctool docs

---

pkg/scyllaclient/client_scylla_integration_test.go

Scyllaclient: use different keyspaces in TestClientDescribeRingIntegration

---

pkg/service/healthcheck/runner.go

Return error from healtcheck runner
---

healthcheck: runner to return error

---

pkg/scyllaclient/client_agent.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_schema.go
pkg/service/cluster/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/util/query/query.go

Fix await schema agreement

---

pkg/scyllaclient/client_agent.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_schema.go
pkg/service/cluster/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/util/query/query.go

This release 3.3 update contains 
- https://github.com/scylladb/scylla-manager/issues/3887
---

Release 3.3 update2

---

pkg/service/backup/backupspec/paths.go
pkg/service/backup/worker_schema.go

Backup: use old driver side describe for older Scylla versions

---

docs/source/conf.py

docs: update latest to branch-3.3

---

docs/source/backup/index.rst
docs/source/backup/specification.rst
docs/source/repair/index.rst
docs/source/restore/compatibility-matrix.rst
docs/source/restore/index.rst
docs/source/restore/old-restore-schema.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst
docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/res.yaml
pkg/managerclient/model.go

Documentation updates for manager-3.3
---

Update docs 3.3

---

pkg/service/restore/restore_integration_test.go

Previously test scenario:
- backup src
- restore to dst
- backup dst
- restore to *dst*
It was changed to (as roundtrip suggests):
- backup src
- restore to dst
- backup dst
- restore to *scr*
Also, src schema is dropped right after the backup, so it should propagate to all nodes before the last restore takes place.
Fixes #3939

Fix TestRestoreSchemaRoundtripIntegration flakiness

---

pkg/service/cluster/service.go

cluster: update to include all hosts into connection validity check

---

pkg/scheduler/scheduler.go
pkg/service/backup/worker_upload.go
pkg/service/repair/generator.go
pkg/service/scheduler/service.go
pkg/service/scheduler/service_integration_test.go

Decidacted scheduler errors

---

pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/provider.go
pkg/scyllaclient/provider_test.go
pkg/service/cluster/model.go
pkg/service/cluster/service.go

Dont create clients simultaneously

---

pkg/scyllaclient/client_rclone.go

Don't return payload on error

---

docs/source/backup/examples.rst

replace "sheduled" with "scheduled"
---

docs: fix a typo

---

pkg/scyllaclient/provider.go

This PR fixes operator tests which were failing since SM 3.3.1.
The failures were connected to 2 things:
- wrong keyspace filtering during the backup fixed in #4000
- SM taking really long time to create a client when many clusters added (and not deleted) to SM were teared down
The second problem was introduced in 634afe81. In order to limit client creation during healthcheck, clients were created under per client cache mutex. This commit indeed made it so no useless clients are created, but because of the per client cache mutex, and not per cluster mutex, it resulted in sequential client creation for separate clusters.
This is especially visible in operator tests, where a single SM handles many single node clusters, most of which have already been teared down. When SM still tries to …

Fix operator tests

---

pkg/service/backup/model.go
pkg/service/backup/testdata/get_target/filter_dc.golden.json
pkg/service/backup/testdata/get_target/filter_dc.input.json

Backward compatibility is less important than correctness.
Rebased on #4034.
Fixes #3922

Don't allow for incomplete backup

---

docs/source/backup/specification.rst

Docs: start backup paths from the root

---

v3/swagger/gen/scylla-manager/models/restore_target.go
v3/swagger/scylla-manager.json

Swagger: add new restore flags to restore target

---

.github/cfg/integration-test-core.yaml
.github/workflows/integration-tests-2023.1.11-IPV4-raftschema.yaml
.github/workflows/integration-tests-2023.1.11-IPV4.yaml
.github/workflows/integration-tests-2023.1.11-IPV6-raftschema.yaml
.github/workflows/integration-tests-2024.1.9-IPV4.yaml
.github/workflows/integration-tests-2024.1.9-IPV6.yaml
.github/workflows/integration-tests-6.1.1-IPV4-tablets.yaml
.github/workflows/integration-tests-6.1.1-IPV4.yaml
.github/workflows/integration-tests-6.1.1-IPV6-tablets.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4-tablets.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4.yaml
.github/workflows/sanity-checks.yml
README.md

gh: reference branch-3.4 in gh actions workflows

---

.github/cfg/integration-test-core.yaml
.github/cfg/main.go
.github/workflows/integration-tests-2023.1.11-IPV4-raftschema.yaml
.github/workflows/integration-tests-2023.1.11-IPV4.yaml
.github/workflows/integration-tests-2023.1.11-IPV6-raftschema.yaml
.github/workflows/integration-tests-2024.1.9-IPV4.yaml
.github/workflows/integration-tests-2024.1.9-IPV6.yaml
.github/workflows/integration-tests-6.1.1-IPV4-tablets.yaml
.github/workflows/integration-tests-6.1.1-IPV4.yaml
.github/workflows/integration-tests-6.1.1-IPV6-tablets.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4-tablets.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4.yaml
.github/workflows/sanity-checks.yml
README.md

This PR is #4151 for `branch-3.4`.

Unify workflows between master and branch

---

pkg/scyllaclient/client_scylla.go
pkg/service/restore/schema_worker.go
pkg/service/restore/tablesdir_worker.go
pkg/service/restore/worker.go
pkg/service/restore/worker_views.go

Apart from fixing #4282, it also fixes the same problem but for awaiting view building completion.
Fixes #4282

Don't wait 10 seconds before calling l&s

---

v3/swagger/gen/scylla/v1/client/operations/storage_service_tablets_repair_post_parameters.go
v3/swagger/scylla_v1.json

Swagger: extend tablet repair API with filtering

---

pkg/service/configcache/service.go
pkg/service/configcache/service_test.go

Fixes #4181
This PR uses netip.Addr to try to parse the host parameter (that can be both, IP or DNS).
If it is able to parse the IP, it keeps this parsed IP (as string) as a key.
If it's not able to parse the IP, original string is kept as a key.
---

fix(config-cache): use netip.Addr to unify the IPv6

---

pkg/cmd/scylla-manager/server.go
pkg/service/configcache/service.go
pkg/service/configcache/service_test.go

Includes:
- https://github.com/scylladb/scylla-manager/pull/4251
- https://github.com/scylladb/scylla-manager/pull/4269
---

Release 3.4.2

---

pkg/scyllaclient/client_scylla.go

Scyllaclient: increase timeout on disabling tablet load balancing

---

docs/source/restore/examples.rst

Adjust restore schema example to CQL schema restore

---

v3/pkg/util/size/sizesuffix.go

This adds pkg/util/sizesuffix package, so it can be shared between pkg/util/managerclient and pkg/service/one2onerestore
---

feat(pkg/util/sizesuffix): add pkg/util/sizesuffix package

---

pkg/scyllaclient/client_scylla.go

Refs #4474
Refs https://github.com/scylladb/scylla-enterprise/issues/5516

[backport 3.6] Scyllaclient: set describe ring API call timeout to at least 5min

---

docs/source/sctool/partials/sctool_backup.yaml
docs/source/sctool/partials/sctool_backup_update.yaml
pkg/command/backup/res.yaml

Point to scylla docs for controlling native backup upload

---

.github/cfg/integration-test-cfg.yaml
.github/workflows/integration-tests-2024.1.20-IPV4.yaml
.github/workflows/integration-tests-2024.1.20-IPV6-raftschema-nossl.yaml
.github/workflows/integration-tests-2025.1.6-IPV4.yaml
.github/workflows/integration-tests-2025.1.6-IPV6-tablets-nossl.yaml
.github/workflows/integration-tests-2025.2.2-IPV4-tablets-native-rclone.yaml
.github/workflows/integration-tests-2025.2.2-IPV6-nossl-rclone-rclone.yaml
README.md
pkg/service/restore/helper_integration_test.go
pkg/service/restore/restore_integration_test.go

This PR updates tested scylla versions.
It also makes necessary adjustments to tests.

.github: bump tested scylla versions

---

go.mod
go.sum
vendor/github.com/gocql/gocql/.gitignore
vendor/github.com/gocql/gocql/.golangci.yml
vendor/github.com/gocql/gocql/Makefile
vendor/github.com/gocql/gocql/cluster.go
vendor/github.com/gocql/gocql/conn.go
vendor/github.com/gocql/gocql/connectionpool.go
vendor/github.com/gocql/gocql/control.go
vendor/github.com/gocql/gocql/exec.go
vendor/github.com/gocql/gocql/frame.go
vendor/github.com/gocql/gocql/helpers.go
vendor/github.com/gocql/gocql/host_source.go
vendor/github.com/gocql/gocql/marshal.go
vendor/github.com/gocql/gocql/metadata_scylla.go
vendor/github.com/gocql/gocql/ring_describer.go
vendor/github.com/gocql/gocql/scylla.go
vendor/github.com/gocql/gocql/serialization/decimal/marshal.go
vendor/github.com/gocql/gocql/serialization/decimal/marshal_utils.go
vendor/github.com/gocql/gocql/serialization/decimal/unmarshal.go
vendor/github.com/gocql/gocql/serialization/decimal/unmarshal_utils.go
vendor/github.com/gocql/gocql/session.go
vendor/github.com/gocql/gocql/tablets/tablet_utils.go
vendor/github.com/gocql/gocql/tracer.go
vendor/github.com/gocql/gocql/uuid.go
vendor/modules.txt

Bump gocql from v1.15.1 to v1.15.3

---

docs/source/backup/index.rst
docs/source/backup/specification.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst

Document alternator backup/restore
