pkg/cmd/agent/main.go
pkg/cmd/scylla-manager/main.go

This works around systemd bug and makes STARTUP ERROR visible in systemctl status.
```
[support@ip-172-31-0-11 ~]$ sudo systemctl status scylla-manager-agent
● scylla-manager-agent.service - Scylla Manager Agent
Loaded: loaded (/usr/lib/systemd/system/scylla-manager-agent.service; disabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Tue 2021-07-06 15:19:12 UTC; 158ms ago
Process: 25147 ExecStart=/usr/bin/scylla-manager-agent (code=exited, status=1/FAILURE)
Main PID: 25147 (code=exited, status=1/FAILURE)
Jul 06 15:19:10 ip-172-31-0-11.eu-central-1.compute.internal systemd[1]: Started Scylla Manager Agent.
Jul 06 15:19:10 ip-172-31-0-11.eu-central-1.compute.internal scylla-manager-agent[25147]: STARTUP ERROR: yaml: unmarshal errors:
Jul 06 15:19:10 …
```

cmt/{agent,scylla-manager}: STARTUP ERROR sleep before exiting (#2823)

---

docs/source/health-check.rst
docs/source/sctool/status.rst
pkg/managerclient/model.go
pkg/service/healthcheck/model.go
pkg/service/healthcheck/service.go
pkg/service/healthcheck/service_integration_test.go
swagger/gen/scylla-manager/models/cluster_status.go
swagger/scylla-manager.json
testing/Makefile
testing/scylla/config/scylla-ssl.yaml

This patchset fixes #2817 and extends `sctool status` command with ERROR status and error details describing the root cause of ERROR or DOWN status. Example
```
sctool status
  Cluster: test (85cd024b-fc9c-47d4-b577-4943cb78a27d)
  Datacenter: dc1
  ╭────┬────────────┬─────────────┬──────────┬────────────────┬──────────┬──────┬──────────┬────────┬──────────┬──────────────────────────────────────╮
  │    │ Alternator │ CQL         │ REST     │ Address        │ Uptime   │ CPUs │ Memory   │ Scylla │ Agent    │ Host ID                              │
  ├────┼────────────┼─────────────┼──────────┼────────────────┼──────────┼──────┼──────────┼────────┼──────────┼──────────────────────────────────────┤
  │ UN │ UP (3ms)   │ ERROR (0ms) │ UP (2ms) │ 192.168.100.11 │ 2h23m36s │ 4    │ 31.11GiB │ …
```

Health check SSL DOWN fix

---

docs/source/conf.py

Since the project is now open, better open issues in this repo (https://github.com/scylladb/scylla-manager/ )  and kill https://github.com/scylladb/scylla-manager-issues

Open new docs issues in this repo

---

pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/metrics_test.go

When buffered channel used for collecting metrics was full,
goroutine trying to write to it was keeping read lock.
Reading side of this channel was deleting metrics which requires taking
a write lock on the same mutex. This resulted in deadlock.
Fixes #2843

healthcheck: fix deadlock during removal of lost nodes metrics (#2843)

---

pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/metrics_test.go

When buffered channel used for collecting metrics was full,
goroutine trying to write to it was keeping read lock.
Reading side of this channel was deleting metrics which requires taking
a write lock on the same mutex. This resulted in deadlock.
Fixes #2843

[2.4] healthcheck: fix deadlock during removal of lost nodes metrics (#2843)

---

pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/metrics_test.go

When buffered channel used for collecting metrics was full,
goroutine trying to write to it was keeping read lock.
Reading side of this channel was deleting metrics which requires taking
a write lock on the same mutex. This resulted in deadlock.
Fixes #2843

[2.5] healthcheck: fix deadlock during removal of lost nodes metrics (#2843)

---

dist/Makefile

In #2810 we started building manager using goreleaser tool.
Once merging i saw an error (also managed to repreduce it locally)
```
fatal: No tags can describe '0b9ff39c6cd145048f1a2f32bbfe15dd335c1001'.
Try --always, or create some tags.
error: tag '2.4-dev-0.20210823.0b9ff39c' not found.
goreleaser --rm-dist --skip-publish --skip-validate
• releasing...
• loading config file       file=.goreleaser.yaml
• loading environment variables
• getting and validating git state
⨯ release failed after 0.02s error=git doesn't contain any tags. Either add a tag or use --snapshot
make: *** [Makefile:21: release] Error 1
```
Looks like i missed this during debug with some other changes
Fixing it here
Related to scylladb/scylla-pkg#2308

dist/Makefile:Fix tag creation during build

---

pkg/managerclient/model.go

Fixes #2842
Example
```
sctool status
Cluster: test (65d9a572-4d94-45e9-a00a-4f55e9c5a689)
Datacenter: dc1
╭────┬─────────────┬─────────────┬────────────┬────────────────┬─────────┬──────┬──────────┬────────┬──────────┬──────────────────────────────────────╮
│    │ Alternator  │ CQL         │ REST       │ Address        │ Uptime  │ CPUs │ Memory   │ Scylla │ Agent    │ Host ID                              │
├────┼─────────────┼─────────────┼────────────┼────────────────┼─────────┼──────┼──────────┼────────┼──────────┼──────────────────────────────────────┤
│ UN │ ERROR (0ms) │ ERROR (0ms) │ DOWN (1ms) │ 192.168.100.11 │ -       │ -    │ -        │ -      │ -        │ da32b3b3-3f01-4642-b16c-37cbbc5df71f │
│ UN │ UP (15ms)   │ UP (14ms)   │ UP (10ms)  │ 192.168.100.12 │ 3h4m33s │ 4    │ …
```

cmd/sctool: status, render hyphen on no data (#2842)

---

dist/etc/scylla-manager.yaml
pkg/config/server_test.go
pkg/config/testdata/server/scylla-manager.yaml
pkg/service/healthcheck/config.go
pkg/service/healthcheck/export_test.go
pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/runner.go
pkg/service/healthcheck/service.go
pkg/service/healthcheck/service_integration_test.go
pkg/service/healthcheck/timeout.go
pkg/service/healthcheck/timeout_test.go

New implementation of dynamicTimeout
- API is changed we no longer return a function to set result, there are two public functions Timeout and Record used by Service and Runners
- The average algorithm is changed from mean to median
- The stddev multiplier is replaced by explicit setting of acceptable time offset to the median value
New config options
```
#healthcheck:
```
Fixes #2801

healthcheck simplification

---

Makefile
pkg/scheduler/activation.go
pkg/scheduler/activation_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

The scheduler package is designed after Quartz project.
It borrows the idea of managing keys and a separation of task properties from the run queue.
Please find the mapping of Quartz core components to scheduler below
- [Job](https://www.quartz-scheduler.org/api/2.4.0-SNAPSHOT/org/quartz/Job.html) - RunFunc
- [JobKey](https://www.quartz-scheduler.org/api/2.4.0-SNAPSHOT/org/quartz/JobKey.html) - Key
- [JobDetail](https://www.quartz-scheduler.org/api/2.4.0-SNAPSHOT/org/quartz/JobDetail.html) - Properties
- [Trigger](https://www.quartz-scheduler.org/api/2.4.0-SNAPSHOT/org/quartz/Trigger.html) - Trigger
The interfaces are decluttered and translated to idiomatic Go.
Renames and customizations are done to better fit the current scheduler infrastructure (pkg/service/scheduler).
Please check …

scheduler: add generic purpose scheduler

---

pkg/service/repair/service.go

Adjust max parallel calculation to [changes in Scylla](https://github.com/scylladb/scylla/commit/4d1c83a4e8130962b1974c754dc1aa03efe65ab5).

service/repair: consider memory bloat when calculate repair parallelism

---

dist/.goreleaser.yaml

Recently we started building Scylla AMI image based on arm architecture.
Follow that, we had QA artifact tests failing due to the fact that they
are trying to install scylla-manager on arm based machines.
Adding the ability to build scylla-manager on both arm and x86 machines

scylla-manager:add arm64 support

---

Makefile
pkg/service/repair/config.go
pkg/service/repair/controller.go
pkg/service/repair/controller_test.go
pkg/service/repair/service.go
pkg/service/repair/worker.go
pkg/service/repair/worker_test.go

When running in row-level repair mode intensity < 1 specifies that there would be less token ranges repaired at the same time but all the shards will need to work in order to repair the token range.
This patch adds auto fallback to legacy mode when intensity < 1.
Fixes #2913

repair fallback to shard-aware (legacy) mode when intensity < 1

---

dist/.goreleaser.yaml

In scylla-manager tar file, we have both the client and agent, Let's remove the `agent` mention so it will less confusing
reported by @ShlomiBalalis

dist/.goreleaser: remove "agent" from tar file

---

ansible/restore/restore.yaml

Fix: #2928
Change ansible section: "Wait for CQL port"

Fix: #2928: change ansible task(Wait for CQL port), add external IP instead of localhost

---

dist/.goreleaser.yaml
dist/Makefile

When running the command `uname -m` we get the machine arch type. Let's
align the reloc package filename to match it

goreleaser:set arch in tar.gz file to match os

---

pkg/cmd/sctool/completion.go

Due to for loop string variable use in an anonymous function all shells generated zsh completion.

sctool: completion, fix

---

pkg/scyllaclient/client.go
pkg/scyllaclient/client_agent_test.go
pkg/scyllaclient/client_rclone.go
pkg/scyllaclient/client_rclone_test.go
pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/retry.go
pkg/scyllaclient/retry_test.go
pkg/scyllaclient/scyllaclienttest/client.go
pkg/scyllaclient/status.go
pkg/scyllaclient/status_test.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_manifest.go
pkg/service/backup/worker_schema.go

This extends the swagger retry code to work with hand created http requests.

scyllaclient retry custom request

---

pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/client_scylla_test.go

Supports:
- Counter (old)
_ Gauge (new)
Fixes #2961

scyllaclient: metrics, support 'memory_total_memory' as gauge

---

pkg/service/repair/service.go

service/repair: disable small tables optimisation if --small-table-threshold is set to 0

---

pkg/cmd/agent/root.go

cmd/agent: require auth-token to start

---

pkg/restapi/cluster.go

sctool: unescape URL encoded cluster name

---

docs/source/sctool/partials/sctool_backup.yaml
pkg/cmd/scylla-manager/server.go
pkg/command/backup/cmd.go
pkg/restapi/task.go
pkg/schema/migrate/v3.0.0.go
pkg/schema/migrate/v3.0.0_integration_test.go
pkg/schema/nopmigrate/nopmigrate.go
pkg/schema/table/table.go
pkg/service/backup/model.go
pkg/service/backup/purger.go
pkg/service/backup/purger_test.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_purge.go
pkg/service/scheduler/model.go
pkg/service/scheduler/service.go
pkg/service/scheduler/service_list.go
schema/v3.0.0.cql

- Allows configuring retention days per backup task
- Purge now handles both removing snapshots over retention policy, and
snapshots older than retention days
- Adds a "deleted" property to tasks so that retention policy is retained
after the task is deleted
Previously the behavior of purge was:
- If retention policy exists (> 0) apply it
- If retention policy does not exist delete snapshot older than
threshold
New behavior is:
- If retention days policy exists (> 0) apply it
- If retention policy exists (> 0) and snapshot was not deleted above apply it
- If neither retention or retention days policy exist delete snapshot
older than threshold
Fixes #2923

service/backup: add retention days

---

dist/.goreleaser.yaml

This is not needed and in Centos it overwrites already existing directory with wrong user and permissions.
The below snippet from rpm installation debug logs happens after the preinstall scriplet.
```
D: create     040755  1 (   0,   0)     0 /var/lib/scylla-manager
```
It does not affect Ubuntu.
Fixes #3032
---

dist: goreleaser, remove empty_folders directive

---

pkg/config/agent/testdata/auth_token_overwrite.golden.yaml
pkg/config/agent/testdata/basic.golden.yaml
pkg/config/agent/testdata/debug_overwrite.golden.yaml
pkg/config/agent/testdata/https_overwrite.golden.yaml
pkg/config/agent/testdata/prometheus_overwrite.golden.yaml
pkg/config/agent/testdata/scylla_overwrite.golden.yaml
pkg/config/agent/testdata/structs_empty.golden.yaml
pkg/rclone/options.go

This prevents rclone from performing a HEAD request for each file when
listing objects.
fixes #3046

rclone: use server mod time by default

---

pkg/scyllaclient/client_rclone.go
pkg/scyllaclient/client_rclone_test.go
pkg/scyllaclient/config.go
pkg/scyllaclient/context.go
pkg/scyllaclient/timeout.go
pkg/scyllaclient/timeout_test.go
pkg/service/backup/list.go

Instead of passing a context into the HTTP request with a 12 hour
timeout, we now set a 5 minute timeout but only enforce it per batch of
files. This is done by waiting for the next JSON decode from the HTTP
request body and selecting between that and a 5 minute timeout each time
we process a new batch, cancelling the context if the timeout is reached.
Had some trouble coming up with a decent way to get this working since we can't really put it in the context, as it needs to be started fresh every time we get something new over the line. Let me know if any feedback on an alternate way to approach this.
Relates to #3039

scyllaclient: t/o per batch on RcloneListDirIter

---

go.mod
go.sum
vendor/github.com/rclone/rclone/fs/operations/operations.go
vendor/modules.txt

- Latest patched version of rclone reduces file copy logs to DEBUG level
fixes #3041

rclone: update rclone dependency to reduce logs

---

pkg/managerclient/model.go
pkg/schema/table/table.go
pkg/service/repair/model.go
pkg/service/repair/service.go
schema/v3.0.0.cql
swagger/gen/scylla-manager/models/repair_progress.go
swagger/scylla-manager.json

Previously if a specific host was specified for a repair that was not
reported in the repair progress and not tracked with a repair run.
Added host to the repair_run table and return that info via the API and
render in the progress output when available.
fixes #3067

managerclient: add host to repair progress details

---

pkg/restapi/restapi.go

Confirmed that panic now prints a stack trace to the logs.

restapi: add recoverer to router

---

.github/workflows/release.yml

The release will trigger by a tag-push and should look like:

CI: add release workflow for auto-generate changelog and release

---

.github/workflows/docs-links.yaml
.github/workflows/docs-pages.yaml
.github/workflows/docs-pr.yaml
.lycheeignore
docs/Makefile
docs/pyproject.toml
docs/source/conf.py

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/395
ScyllaDB Sphinx Theme 1.2 is now released 🥳 
We’ve added automatic checks for broken links and introduced numerous UI updates.
You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022).
1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).
2. Enter the docs folder, and run:
```
make preview
````
4. Open http://127.0.0.1:5500/ with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.2.x``:

docs: update theme 1.2.1

---

pkg/scheduler/trigger/cron_test.go
pkg/scheduler/window.go
pkg/scheduler/window_test.go

Previously we were calculating execution times by simply adding a
`time.Duration` to 00:00 on the execution day. Most of the time this
works, however on days where DST begins or ends it does not. For
example 21:00 is not always 21 hours after 00:00, sometimes it can
be 20 or 22 hours after.
In order to account for this we are now creating a new time using the
hours from duration and the location instead of simply adding it.
Also fixed an issue with a test that does not account for DST changes,
sometimes EST and CET are not 6 hours apart but instead 5 or 7 because
the clocks change on different dates.
fixes #3082

scheduler/window: Account for DST changes

---

pkg/service/scheduler/service.go
pkg/service/scheduler/service_suspend.go

If a task is created with a window but not any type of schedule it
should begin execution when the window begins. In the case where the
scheduler is suspended or stopped before the execution that was never
happening. This makes sure we check if a task created in that way gets
scheduled on a resume if the task has never run.
fixes #3083

service/scheduler: schedule one off tasks on resume

---

pkg/managerclient/model.go

As far as I can tell this limit really didn't bring any benefit to begin
with. Every status is almost as short as the table header "Status"
anyway and the other columns in the table are much longer and more
likely to cause the lines to wrap. There is also only a 1-2 width window
where this could actually be beneficial, and in other cases it leads to
every status showing as "…" which can cause confusion.
fixes #3065

managerclient: don't limit status column

---

pkg/restapi/task.go

this validation was only occurring on creation of a new task and not being checked when updating an existing task.
fixes #3095

restapi/task: validate task on update and create

---

pkg/service/backup/purger.go

We use an identical log message in 4 places which makes it difficult to
determine what code was executed based on the logs. Adding some unique
text to each so that the logs are more traceable.

service/backup: differentiate between log msgs

---

.github/workflows/docs-links.yaml

Related issue https://github.com/scylladb/scylla-manager/issues/3121
Only check for broken links within the docs folder.

docs: link checker skip vendor dir

---

dist/.goreleaser.yaml

Since 68c99a6c7ede5db83db1f423b1bc71b435a85f11, the output of
`sctool version` is:
```
Client version: Snapshot
Server version: Snapshot
```
it was breaking the dtest run since it was merged
---

Fix version command `sctool version` output

---

dist/etc/scylla-manager.yaml
pkg/cmd/scylla-manager/server.go
pkg/config/server/server.go
pkg/config/server/server_test.go
pkg/config/server/testdata/scylla-manager.yaml
pkg/scyllaclient/config.go
pkg/service/cluster/service.go

I created an additional struct containing only the user-configurable
parts of the client config, and embedded them within the config. This is
because fields like Hosts and Port are populated from the cluster and
they would just be overriden if exposed in the configuration.
fixes #3112

scyllaclient: expose config to config file

---

pkg/service/backup/backupspec/location.go

Fixes underscores in backup paths not being accepted
```
Command: 'sudo sctool backup -c b25d296b-52ea-4e01-9c7c-5761b00aaaa9 --location s3:manager-backup-tests-us-east-1/path_testing/ '
Exit code: 1
Stdout:
Stderr:
Error: malformed request: evaluate properties: extract retention for task b31aadce-b2f2-4432-8562-ab258361082d: invalid location "s3:manager-backup-tests-us-east-1/path_testing/", the format is [dc:]<provider>:<path> ex. s3:my-bucket, the path must be DNS compliant
Trace ID: CBTa_n9hQE2dCA-SWvNKvw (grep in scylla-manager logs)
```

service/backup: allow underscores in backup paths

---

docs/source/sctool/partials/sctool_info.yaml
pkg/command/info/cmd.go
pkg/command/info/res.yaml
pkg/command/legacy/task/taskhistory/cmd.go
pkg/managerclient/model.go

Default to not printing cause of errors, and if we do print them add a
limit to the field.
Legacy command always prints cause.
Fixes #3140

command/info: add cause flag and limit error field

---

.github/workflows/release.yml

Following #3097 the tag pattern should align to v.x.y.z

ci: align release tag pattern

---

pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go

error is now much more useful and succinct:
```
$ ./sctool backup -L "s3:fake-bucket"
Error: create backup target: specified bucket does not exist
Trace ID: 8KpElsLlRcaRjnW7y3ysJw (grep in scylla-manager logs)
```
fixes #3139

service/backup: improve error for nonexistent bucket

---

pkg/service/backup/service_backup_integration_test.go

Simple fix for randomly failing TestPurgeTemporaryManifestsIntegration.
SnapshotID is generated out of timestamp with to one second precision.
It happened sometimes that two backups done in TestPurgeTemporaryManifestsIntegration had same snapshotID and test was failing due to that.
---

service/backup: integration test, fix TestPurgeTemporaryManifestsIntegration

---

.golangci.yml
Makefile
pkg/cmd/scylla-manager/main.go
pkg/cmd/scylla-manager/root.go

Fixes #3204 
Signal handling is moved before the migration starts.
Additional commit - change os.Exit to syscall.Exit (no need to log panic on closing server, it's actually expected)
---

Handle signals during migrate

---

go.mod
go.sum
vendor/github.com/rclone/rclone/fs/operations/operations.go
vendor/modules.txt

Fixes #3209 
Change comes from scylladb/rcone repo.
This PR just updates the rclone dependency.
---

rclone: reduce info logs on delete actions

---

testing/Makefile
testing/docker-compose.yaml

UID is a readonly system variable, so it can't be assigned and passed to docker-compose file

testing: makefile, docker-compose, changed UID to CURRENT_UID

---

pkg/service/backup/list.go
pkg/service/backup/service.go

Iterating over Index should be done using ForEachIndexIter or ForEachIndexIterFiles.
Commit 4dc88bebb68c549a010ff3e66fa7891fa0c39346 introduced a new way of processing Index file that consumes less memory. Normal iteration over Index has been replaced with either ForEachIndexIter or ForEachIndexFiles (especially in all uses of ForEachManifest method).
Unfortunately, ForEachManifest hasn't been changed so it still loads the whole index to memory, only for ForEachIndexIter to load it again (I guess someone forgot to delete this part).

service/backup: forEachManifest no longer loads Index into memory

---

docs/source/index.rst
docs/source/install-scylla-manager-agent.rst
docs/source/install-scylla-manager.rst
docs/source/older-versions.rst
docs/source/scylla-monitoring.rst
docs/source/upgrade/index.rst

The Manger section in the ScyllaDB docs has been removed; see https://github.com/scylladb/scylladb/pull/11162. 
This PR removes or replaces the links to that section.
In addition, I've replaced "Scylla" with "ScyllaDB" on key pages to be in sync with other resources.

doc: remove outdated refrences to the Manager section in the ScyllaDB docs

---

pkg/cmd/agent/router.go

Fixes #3235 
More info https://github.com/scylladb/scylladb/issues/9701
---

promproxy: use scylla listen address when prometheus address missing

---

pkg/service/repair/controller.go
pkg/service/repair/generator.go

Fixes flaky `TestServiceRepairIntegration/kill_repairs_on_task_failure/when_task_is_cancelled` integration test.
Actually the test is correct, but the code that suppose to handle _context.Done()_ signal doesn't give the priority to _context.Done()_, but it's possible that select clause will choose different branch.
It's fixed here.
---

service/repair: fix on generator way of context.Done handling

---

.github/workflows/release.yml

Following 79107c2e351458339e6e91129f4f002f0909bd81 , we don't really need to publish docker images since it's been done by our Jenkins job. Adding `--skip-publish` so the release in GitHub will be created

CI: skip publish docker during release creation

---

pkg/cmd/agent/benchmark.go

This PR fixes the way in which command `./scylla-manager-agent benchmark` initializes rclone.
It used to set rate limit in a way that it didn't have any effect on actual download conducted by rclone.

agent/benchmark: fixed rclone initialization

---

pkg/scyllaclient/client_scylla.go

Part of https://github.com/scylladb/scylladb/issues/11938
---

service/backup: extend scylla snapshot api call timeout to 30m

---

dist/.goreleaser.yaml
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Adding arm support to our Scylla-manager docker image
This will only build additional docker image, the publishing part will be done as part of https://github.com/scylladb/scylla-pkg/issues/3239
Closes: https://github.com/scylladb/scylla-manager/issues/3278

.goreleaser: add support for arm based docker image

---

dist/Makefile

Changing dist version to 3.2-dev due to coming release of scylla-manager-3.1
---

release: builds from master to be part of 3.2-dev

---

cloud/backup-cleaner/main.go

This PR fixes code in living **cloud** directory that couldn't compile since aa7cc731.
This part of code isn't used by Scylla Manager so it was unfortunately missed when refactoring given function.

backup-cleaner: fixed code that couldn't compile since aa7cc731

---

pkg/command/flag/flag.go
pkg/command/flag/task.go
pkg/command/flag/type.go
pkg/command/flag/type_test.go
pkg/service/scheduler/service.go

Legacy Trigger uses both `startDate` and `interval` to calculate next activation of given task, so even when `--start-date` isn't specified by the user (but the `--interval` flag is), it should be set to `now` and inserted to DB. Without it SM cannot correctly calculate next task activation after restart.
Fixes #3283

Fix scheduling of task with --interval and without --start-date

---

docs/source/repair/examples.rst

There is a small bug in repair example documentation originating from copying some examples from backup procedure.
Fixes #3229

Fixed repair example documentation

---

dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Move docker images to be based on ubuntu:22.04
Closes: https://github.com/scylladb/scylla-manager/issues/3305

docker: move to ubuntu22.04 based image

---

pkg/service/repair/worker.go

SM kept on retrying to query repair status even when encountering context cancellation or deadline exceeded.
This caused it to loop indefinitely in case Scylla is overloaded.

Fix non  ending repair runs

---

pkg/service/repair/worker.go

It's equally important as 'Repairing' message and would help to debug on production where default log level is info.

service/repair: use info log level for repair done message

---

pkg/service/backup/restore_worker_schema.go

Since gocql does not support `alter` queries, the restore procedure uses `ExecStmt` instead of query builder, which requires that we wrap unusual keyspace and table names in quotes (e.g. `keyspace_name=10gb_sizetiered`).
Fixes #3316

Wrap table name in quotes when using CQL in restore

---

testing/nodes_cp
testing/nodes_exec

With the latest version of docker I use on my machine, 
`docker ps -f name=scylla_manager_dc --format {{.Names}}` is not able to find test scylla containers.
It's because docker uses `-` instead of `_` to create container name.
It's changed to be filtered against "dc1_node" and "dc2_node" names instead.
---

testing: different filter for finding test scylla containers

---

pkg/config/agent/agent_test.go
pkg/config/agent/testdata/auth_token_overwrite.golden.yaml
pkg/config/agent/testdata/basic.golden.yaml
pkg/config/agent/testdata/debug_overwrite.golden.yaml
pkg/config/agent/testdata/https_overwrite.golden.yaml
pkg/config/agent/testdata/prometheus_overwrite.golden.yaml
pkg/config/agent/testdata/scylla_overwrite.golden.yaml
pkg/config/agent/testdata/structs_empty.golden.yaml
pkg/rclone/options.go
pkg/scyllaclient/client_rclone_test.go

Follow up to https://github.com/scylladb/scylla-manager/issues/3288
It changes SizeOnly flag on RClone to false.
SizeOnly = false means that RClone is going to compare files checking their checksum as well, not size only.
---

rclone: overwrite when checksum is different

---

pkg/service/backup/restore_worker.go
pkg/service/backup/restore_worker_data.go

Batches are too big.
Number of shards is completely irrelevant for restore.
It's a cherry pick from https://github.com/scylladb/scylla-manager/pull/3331
---

restore: do not include no shards into batch_size

---

pkg/scyllaclient/client_ping.go

This PR adds validation of UN state for nodes which will be performing restore. Drained nodes cannot use load and stream, so this change is necessary.
Fixes #3344
Fixes #3342
This type of validation might be additionally required in restore schema workflow in #3339

Additional validation for restore hosts

---

pkg/service/backup/backupspec/versioning.go
pkg/service/backup/restore.go
pkg/service/backup/restore_progress.go
pkg/service/backup/restore_worker.go
pkg/service/backup/restore_worker_data.go
pkg/service/backup/restore_worker_schema.go
pkg/service/backup/restore_worker_tables.go
pkg/service/backup/service_backup_restore_integration_test.go

This PR separates workflow of restoring schema and tables. The main differences are:
- restoring tables requires altering ggs which is forbidden on schema tables
- restoring schema duplicates data across all nodes in order to simulate repair
- restoring schema cannot be resumed and monitoring of its progress is rather weak
- restoring schema does not show data duplication on metrics and progress
Even though it might look like a regression, restoring schema should have much bigger success ratio with those changes.
Sorry for such a big commit, but those changes couldn't really be divided because of all the refactor that needed to be done at once.

Separate restoring schema and tables

---

pkg/service/backup/restore.go
pkg/service/backup/service_backup_restore_integration_test.go
pkg/service/backup/testdata/restore/get_target/continue_false.golden.json
pkg/service/backup/testdata/restore/get_target/default_values.golden.json
pkg/service/backup/testdata/restore/get_target/schema.golden.json
pkg/service/backup/testdata/restore/get_target/tables.golden.json

We cannot restore CDC tables because SM cannot alter them and ensure data consistency.
Fixes #3347

Do not restore CDC tables

---

pkg/service/backup/restore.go
pkg/service/backup/restore_worker_tables.go
pkg/service/backup/service_backup_restore_integration_test.go
pkg/service/backup/testdata/restore/get_target/continue_false.golden.json
pkg/service/backup/testdata/restore/get_target/default_values.golden.json
pkg/service/backup/testdata/restore/get_target/tables.golden.json

This PR fixes bug in restore cdc tables blacklisting.
Moreover, it adds test for restoring Scylla tables `system_auth.* system_traces.* system_distributed.service_levels`.

Tests for restoring scylla tables

---

.github/actions/test-setup/action.yml
.github/workflows/go.yml
testing/Makefile

This PR refactors environment set up, so that it's cleaner and reusable.
It also makes github actions run each pkg test in a separate job in parallel. 
In order to further improve performance:
- backup and restore tests have been separated into different jobs (even though they live in the same pkg #3381)
- restore tables tests and restore schema tests have been further divided into different jobs (because both of them take huge amount of time)
- tests for smaller packages have been merged into one job (we don't need to set up env for each of them separately)
Fixes #3372

Run integration tests in parallel in github actions

---

dist/.goreleaser.yaml
dist/Makefile

During local build i noticed the following warning
```
• DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
• DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
• DEPRECATED: `archives.replacements` should not be used anymore, check https://goreleaser.com/deprecations#archivesreplacements for more info
• DEPRECATED: `nfpms.replacements` should not be used anymore, check https://goreleaser.com/deprecations#nfpmsreplacements for more info
• DEPRECATED: `nfpms.replacements` should not be used anymore, check https://goreleaser.com/deprecations#nfpmsreplacements for more info
• DEPRECATED: `nfpms.replacements` should not be used anymore, check …
```

dist/Makefile: switch to `--clean` instead of `--rm-dist`

---

dist/.goreleaser.yaml

Following the changed made in #3391, the manager build failed since it was not aligned with Scylla-pkg.
Reverting those changes only for relevant packages

dist/.goreleaser: fix deb packages prefixes

---

README.md

After https://github.com/scylladb/scylla-manager/pull/3436, it is possible to run ipv6 environment and run tests on it.
It is not documented, so adding docs

readme: mention IPv6 environment

---

pkg/service/backup/restore.go
pkg/service/backup/restore_worker.go

We didn't explicitly validate that all tables are still present in the restore destination cluster after resume. 
It wasn't big of an issue (restore would eventually run into deleted table and return some error), but it's always better to check it before resuming the restore and not in the middle of it.
Related [issue](https://github.com/scylladb/scylla-dtest/issues/3286) from dtests.

Validate that all units are present after resume

---

pkg/managerclient/model.go
pkg/managerclient/restore.go
pkg/service/backup/backupspec/stage.go
pkg/service/backup/service_backup_restore_integration_test.go

The following [dtest](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-dtest/lastCompletedBuild/testReport/manager_restore_tests/TestScyllaMgmtRestore/test_restore_alter_batch_size/) was querying restore progress right after task creation, which resulted in getting nil RestoreProgress.Progress, which caused panic when displaying restore progress. This PR fixes this behavior.

Fix restore progress display with nil progress

---

pkg/service/backup/restore_worker_tables.go
pkg/service/backup/service_backup_restore_integration_test.go
pkg/service/repair/service.go

Repair task ends with an error when there is nothing to repair (e.g. repaired tables are not replicated).
In this case, restore procedure should just skip this step and not display any repair progress.
This PR fixes that and adds a test, which tries to restore data into non-replicated keyspace (this test fails without provided fix).

Fix empty post-restore repair

---

pkg/metrics/backup.go
pkg/service/backup/restore.go
pkg/service/backup/restore_worker_index.go
pkg/service/backup/restore_worker_tables.go
pkg/service/backup/restore_worker_tables_test.go

closes https://github.com/scylladb/scylla-manager/issues/3397
This PR introduces a new `progress` metric that reports progress of the restore process for a given `backup.RestoreTarget` target
Used 100MB backup to test this metric locally, here's the outcome.

Add metric to report progress of the restore process

---

pkg/schema/table/generate.go

Fixes #3473 
+ fixes current gh actions failures
---

generate: link to schemagen binary

---

testing/scylla/config/scylla-second-cluster.yaml
testing/scylla/config/scylla.yaml

After https://github.com/scylladb/scylla-manager/pull/3436 cluster nodes are bootstrap one by one to ensure stability As result test env boostraping too long.
Fortunately there is a way to make skylla load faster via `skip_wait_for_gossip_to_settle` which makes it not to wait for gossip to settle, which readuces load time 5 fold
Closes https://github.com/scylladb/scylla-manager/issues/3472

fix(testing): make scylla load faster

---

testing/scylla/config/scylla-second-cluster.yaml
testing/scylla/config/scylla.yaml

Reverts scylladb/scylla-manager#3483
Unfortunately I it made restore tests to fail:
```
-- When: query contents of restored table
service_backup_restore_integration_test.go:1024: restoretest_full.big_table, srcCount = 512, dstCount = 512
service_backup_restore_integration_test.go:1024: system_auth.role_attributes, srcCount = 1, dstCount = 1
service_backup_restore_integration_test.go:1024: system_auth.role_members, srcCount = 1, dstCount = 1
service_backup_restore_integration_test.go:1024: system_auth.role_permissions, srcCount = 5, dstCount = 18
service_backup_restore_integration_test.go:1024: system_auth.roles, srcCount = 3, dstCount = 4
service_backup_restore_integration_test.go:1024: system_distributed.service_levels, srcCount = 1, dstCount = 1 …
```

Revert "fix(testing): make scylla load faster"

---

Makefile
pkg/service/backup/restore_worker_tables.go
pkg/service/backup/service_backup_restore_integration_test.go
pkg/service/repair/generator.go
pkg/testutils/db/db.go
testing/Makefile
testing/docker-compose-ipv4.yaml
testing/docker-compose-ipv6.yaml
testing/docker-compose.yaml

This PR add an additional node to restore src cluster. This results in:
- changing tests so that we restore into ks with identical schema as in src
- improve overall restore tests quality
Because of the #3481, master wasn't green recently, so this PR also fixes minor implementation bugs and fixes flaky tests (more info in commit messages).
Related #3466 
Possibly related #3485
Fixes  #3479

Fix restore tests

---

pkg/scyllaclient/config_client.go

fix(scyllaclient): report correct password protection status with full authenticator name

---

testing/Makefile

We should use advised 1GB per shard in testing env in order to avoid misleading errors.
Fixes #3478

Testing: increase memory to 1GB per shard

---

docs/source/sctool/index.rst

Fixes https://github.com/scylladb/scylla-manager/issues/3366
This PR clarifies the usage of `sctool` command flags. It adds an explanation, as well as examples.
In addition, it replaces "Scylla" with "ScyllaDB".

doc: clarify the usage of sctool flags

---

pkg/service/backup/restore_worker.go

Gocritic complaints:
```
Error: pkg/service/backup/restore_worker.go:154:4: nestingReduce: invert if cond, replace body with `continue`, move old body after the statement (gocritic)
if restoredTables.Has(index.KeyspaceName + "." + index.TableName) {
^
Error: pkg/service/backup/restore_worker.go:182:4: nestingReduce: invert if cond, replace body with `continue`, move old body after the statement (gocritic)
if restoredTables.Has(view.KeyspaceName + "." + view.BaseTableName) {
^
make: *** [Makefile:[8](https://github.com/scylladb/scylla-manager/actions/runs/5671867688/job/15369867018#step:4:9)4: .check-lint] Error 1
Error: Process completed with exit code 2.
```

fix(backup): make gocritic happy

---

pkg/managerclient/model.go
pkg/restapi/cluster.go
pkg/restapi/cluster_test.go
pkg/restapi/mock_clusterservice_test.go
pkg/restapi/services.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go
pkg/store/rollback_test.go
pkg/store/store.go
pkg/store/store_integration_test.go

Output of this command has been updated with additional column "CQL credentials" which indicates if SM have CQL credentials for given cluster. We don't want to print credentials or even directly query them (use 'COUNT(*)' instead of regular column) for security reasons.
Fixes #3531

Extend sctool cluster list with CQL credentials

---

pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/client_scylla_integration_test.go
pkg/service/repair/progress.go
pkg/service/repair/progress_integration_test.go
pkg/service/repair/service.go
pkg/service/repair/service_integration_test.go
pkg/service/repair/testdata/AggregateProgressIntegration/empty_progress_list.golden.json
pkg/service/repair/testdata/AggregateProgressIntegration/multiple_progress_multi_host.golden.json
pkg/service/repair/testdata/AggregateProgressIntegration/single_progress_single_host.golden.json
pkg/service/repair/worker.go

This PR fixes situations when repair task created before SM 3.2 and started after upgrading to 3.2 displayed wrong progress. With those changes, it should work fine even for paused repair tasks resumed after the upgrade.
Fixes #3534

Fix repair schedule

---

pkg/ping/cqlping/cqlping.go
pkg/ping/cqlping/cqlping_integration_test.go
pkg/ping/cqlping/cqlping_test.go
pkg/service/healthcheck/service.go

Fixes #3550 
Customers complain that healthcheck fails on cqlping having almost no load on the cluster and network working perfectly fine.

fix(healtcheck): make native cql to retry if connection is failed

---

go.mod
pkg/sstable/sstable_naming.go
pkg/sstable/sstable_naming_test.go

before this change, `RandomSSTableUUID()` just return a serial of random bits formatted like 'xxxx_xxxx_xxxxxxxxxxxxxxxxxx', where 'x' is picked from the alphabet of
"abcdefghijklmnopqrstuvwxyz0123456789".
but the generated UUID cannot be decoded by scylla, as it does not encode a UUID v1 (as per RFC4122). that's why scylla chokes when parsing the UUID created by scylla-manager, and throws `std::out_of_range (stoull)`.
in this change, we
* add github.com/google/uuid as an explicit dependency
* leverage github.com/google/uuid to generate a UUID V1, and format it with the same encoding used by scylla's `generation_type`.
Fixes https://github.com/scylladb/scylladb/issues/15226
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>
---
Please …

fix(backup): generate a proper UUIDv1 for sstable identifier

---

pkg/cmd/agent/log.go
pkg/cmd/agent/metrics.go
pkg/cmd/agent/router.go
pkg/cmd/agent/router_test.go
pkg/cmd/agent/server.go

Logging all requests overpopulates logs, so it's better to log only log requests with error status code. In order to make up for this loss of information, agent populates `scylla_manager_agent_http_status_code` metric with counter of http requests with their response status code.
Fixes #3451
Fixes #3125

Reduce agent log spam

---

dist/scripts/scyllamgr_setup

When testing ScyllaDB 2023.1.0 and Scylla Manager 3.2.0 I've encountered and issue of insufficient memory being available to ScyllaDB used by Scylla Manager to store its internal data, this resulted in ScyllaDB not being able to start up properly. I propose to change it to `500M` according to https://github.com/scylladb/siren/pull/9602#issuecomment-1694659667

feat(scylladb): increase memory limit for ScyllaDB to 500M

---

dist/systemd/scylla-manager-agent.service
dist/systemd/scylla-manager.service

Closes #3561 
Time to time it can happen that agent and server are failing on the start.
To exclude all temporary cases `RestartPreventExitStatus` is removed to make systemd restart them automatically
And `StartLimitBurst` is set, to make systemd not to start them if problem is not going away

fix(systemd-files): make it restart on non-zero exit

---

pkg/command/repair/cmd.go
pkg/managerclient/error.go
pkg/restapi/error.go
pkg/restapi/error_test.go
pkg/restapi/task.go
pkg/scyllaclient/client_scylla.go
swagger/gen/scylla-manager/models/error_response.go
swagger/scylla-manager.json

Fixes https://github.com/scylladb/scylla-manager/issues/3568
CLI error message is extended and contains information about the reason why task creation failed.
```
One of the nodes is down. Task cannot be created.
Check --ignore-down-hosts flag if you wish to exclude the node from the repair.
Error: create repair target: create repair plan: calculate tables size: fetch table disk size report
192.168.200.12: giving up after 2 attempts: agent [HTTP 502] 
invalid response from host
Trace ID: Qs_yl1nOSXiWTwr0J7Oh6Q (grep in scylla-manager logs)
```
---

Better explanation on host down

---

pkg/service/repair/progress_integration_test.go

As we can see in the issue, this test can sometimes fail on duration comparison limit. Those tests were originally written for local testing envs and were rekicked in case of failures, so I think that simply increasing the timeout should do the trick.
Fixes #3573

Repair test: extend duration cmp limit (#3573)

---

pkg/service/repair/generator.go
pkg/service/repair/plan.go

This PR improves observability  and control over repair small table optimization.
Those changes seems to be useful when dealing with #3584.

Repair: small table optimization improvements

---

dist/.goreleaser.yaml
dist/Makefile

This PR contains the following commits:
- 3ed75f391d3e3efb04291ffa8a78243e95e0bada - Makefile: bump dev version to 3.3.0
- a7cb3318f221fe4fbda42f9803c9b29d89962ddb - Remove warning during build

Bump dev version and remove warnings during build

---

testing/scylla-manager-agent/scylla-manager-agent-ipv6.yaml
testing/scylla-manager-agent/scylla-manager-agent.yaml

By default, agent samples logs, so it only saves first occurrence of a similar log message in a given time frame.
I believe that it would be better to disable it for testing, so that we don't miss any logs there.

Testing: disable agent log sampling

---

pkg/service/backup/service_backup_integration_test.go

Recently github actions backup tests have been failing because of the 'not enough disk space' error ([example](https://github.com/scylladb/scylla-manager/actions/runs/6447344099/job/17563303813?pr=3602)).
Decreasing required disk space from 10% to 5% should solve this issue.

Testing: decrease min disk space for backup

---

dist/.goreleaser-docker.yaml
dist/.goreleaser.yaml
dist/Makefile
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

In this PR we moved all docker-related build processes back to goreleaser, so build, publish and manifest creation (which we need to support multi-arch images) will be done here instead of `Scylla-pkg`.
Since we always want to publish our docker images (including in master) I have created a dedicated yaml file configuration for our docker build process
As a result, for releases only, we will be able to publish the release to GitHub
Closes: https://github.com/scylladb/scylla-manager/issues/3278
**This should be merged together with https://github.com/scylladb/scylla-pkg/pull/3615**

manager: Adding docker multi-arch support

---

pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_index.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/db/db.go

Alternator tables with dashes in their name weren't backed-up, because of incorrect regex in backup index stage.
This PR fixes that and add tests for:
- backup with alternator table
- restore schema and tables with alternator table
Fixes #3165

Fix alternator backups

---

.github/workflows/release.yml

release workflow suppose to skip publish when new tags are being pushed
but we get the following warning
```
/opt/hostedtoolcache/goreleaser-action/1.21.2/x64/goreleaser release --skip-publish
• starting release...
• loading                                          path=.goreleaser.yaml
• DEPRECATED: --skip-publish was deprecated in favor of --skip=publish, check https://goreleaser.com/deprecations#-skip for more details
• skipping announce and publish...
```
Modify the workflow so we will skip the publish part

[release workflow]:modify publish args

---

pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_index.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/db/db.go

Except for fixing reopened (because of dots in table names) issue, this PR also adds a small repair test which validates that alternator tables are also repaired.
Fixes #3165

Fix alternator tables with dots

---

pkg/service/repair/controller.go
pkg/service/repair/controller_test.go
pkg/service/repair/generator.go
pkg/service/repair/service.go
pkg/service/repair/worker.go
pkg/util/workerpool/pool.go
pkg/util/workerpool/pool_test.go

This is the first step in implementing #3611, as changing the approach to repair parallelism (while still integrating it with `sctool repair control`) requires freely control the size of the worker pool, which was lacking in the current implementation.

Add worker pool to repair

---

dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Similar to https://github.com/scylladb/scylladb/issues/16222 ,we need to make sure our docker image is updated to the latest for all OS packages
Fixes: https://github.com/scylladb/scylla-manager/issues/3646

dockerfile: add `apt-get upgrade` during build

---

CODEOWNERS

Give the ownership of /dist to release engineering.
---

fix(codeowners): dist part for release engineering

---

docs/source/_templates/local-scripts.html

Related https://github.com/scylladb/sphinx-scylladb-theme/pull/949
Adds the Zendesk tag for the docs.
1. Build the docs.
1. Open them in the browser.
1. Inspect the code.
1. You should see the project-specific tag loaded:

docs: Add Zendesk tag 

---

docs/source/conf.py

Related: https://github.com/scylladb/sphinx-scylladb-theme/pull/979
Adds the Zendesk tag to index.html page.
1. Run `make multiversion`.
1. Open the `_build/dirhtml/index.html` file.
1. Check for the presence of the Zendesk tag associated with this project.

docs: add zendesk tag to index.html

---

docs/source/restore/restore-schema.rst

There is no need to do that as it is performed automatically.
Actually, this has been a part of SM for quite some time already.
In response to [comment](https://github.com/scylladb/scylla-enterprise/issues/3706#issuecomment-1864611316).
Fixes #3676

Remove hint about recreating MV and SI from restore schema

---

pkg/scyllaclient/client_scylla.go
pkg/service/repair/worker.go

Both of those calls return from Scylla only when the job is done. Because of that SM shouldn't timeout them on its side (even though it usually works when backoff retry is used).
This PR also includes a small improvement of repair logs mentioned in [here](https://github.com/scylladb/scylla-manager/issues/3671#issuecomment-1870061453).
Fixes #3675

Fix timeouts in RepairStatus and LoadSSTables

---

pkg/command/flag/type.go
pkg/service/repair/controller.go
pkg/service/repair/controller_test.go
pkg/service/repair/model.go
pkg/service/repair/plan.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go

There are still some bugs (one described in the issue below) regarding using float intensity. In order to get rid of them, we should only tolerate float intensity at the entrypoint, but completely remove it from SM repair internals (both in service and progress display).
We keep float intensity in task properties and in swagger endpoint parameters, but we convert it to int intensity as a first thing in internals, which happens in:
- GetTarget (from task properties)
- sctool repair control endpoint (from query param)
Fixes #3665

Fix repair float intensity

---

.github/workflows/go.yml
.github/workflows/integration-tests.yaml
Makefile
pkg/service/backup/service_backup_integration_test.go
pkg/service/repair/preference.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/schema_worker.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/worker.go
testing/.env
testing/Makefile
testing/docker-compose.yaml
testing/scylla/Dockerfile

Just running to see test output, but enterprise releases should definitely be included in test matrix.

Run gh actions on enterprise Scylla

---

docs/source/conf.py

This PR fixes the Zendesk tag that makes it possible to search the docs via Zendesk.
See https://github.com/scylladb/scylla-manager/pull/3685#issuecomment-1897584039

doc: fix the zendesk tag

---

docs/source/docker/Dockerfile
docs/source/docker/docker-compose.yaml

Previously I wasn't able to follow our docker setup [example](https://manager.docs.scylladb.com/stable/docker/index.html) because of two reasons:
- too little memory assigned to SM DB
- incorrect `echo` behavior when writing config files
Now it should work fine.
Fixes #3672

Update docker setup example

---

pkg/scyllaclient/client_agent.go
pkg/scyllaclient/client_agent_test.go
pkg/service/cluster/service.go
pkg/service/healthcheck/service.go

Previously, SSL was preferred when client_encryption_options.enabled
coming from ScyllaDB configuration was true and SSL port is open,
even when Scylla Manager did not have any client certificate registered
for particular cluster.
This caused issues when ScyllaDB cluster was exposing both CQL and CQL
SSL with mTLS, because even when Manager was not registered with
certificates, it still insisted to establish sessions using SSL port.
CQL healthchecks was also affected.
It can be further improved by implementing #3679 which will add a switch deciding whether user wants to use either SSL or non SSL port.
Fixes https://github.com/scylladb/scylla-manager/issues/3698

Require certificate registered within cluster before choosing CQL SSL

---

pkg/cmd/scylla-manager/server.go
pkg/service/cluster/service.go
pkg/service/healthcheck/service.go
pkg/service/healthcheck/service_integration_test.go

fix(healtcheck): respect force-tls-disabled and force-non-ssl-session-port cluster properties

---

docs/source/sctool/partials/sctool_backup.yaml
docs/source/sctool/partials/sctool_backup_update.yaml
docs/source/sctool/partials/sctool_backup_validate.yaml
docs/source/sctool/partials/sctool_backup_validate_update.yaml
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_update.yaml
docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
docs/source/sctool/partials/sctool_suspend.yaml
docs/source/sctool/partials/sctool_suspend_update.yaml
pkg/cmd/scylla-manager/tasks.go
pkg/command/flag/task.go
pkg/command/flag/task.yaml
pkg/service/scheduler/model.go
pkg/service/scheduler/model_test.go
pkg/service/scheduler/service.go
swagger/gen/scylla-manager/models/schedule.go
swagger/scylla-manager.json

Fixes #3701 
Fixes #3700 
This PR deprecates the `interval` param in swagger, `interval` flag in SM codebase.
Besides that, this PR extends Cron to include start date.
`start_date` mixed with `cron` is interpreted as "Run the task frequently according to cron spec, but the first execution must happen after `start_date`".
Fixes #3702 
This PR removes check on start_date when the interval flag is not introduced. More details https://github.com/scylladb/scylla-manager/issues/3702#issuecomment-1952938525
**How it was tested ?**
Integration tests (part of CI) (expected 4 to fail, schema restore in 5.4 and its enterprise equivalent)
Added unit tests to cover new functionality.
---
- …

Deprecate interval and mix start_date with cron

---

dist/etc/scylla-manager.yaml
pkg/cmd/scylla-manager/server.go
pkg/config/server/server.go
pkg/config/server/server_test.go
pkg/schema/table/table.go
pkg/scyllaclient/client_scylla_test.go
pkg/scyllaclient/context.go
pkg/scyllaclient/provider.go
pkg/scyllaclient/provider_test.go
pkg/service/cluster/model.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go
pkg/service/healthcheck/service_integration_test.go
schema/v3.2.6.cql

Fixes #3707
This PR changes how the Scylla API client is created.
Previously, as Scylla Manager stores all known hosts in the DB, it was passing all of them to the API client initially upon creation. The client then called one of the endpoints to discover available hosts. This approach could lead to non-existing IPs being passed during client creation, and failure when calling the specified endpoint would later indicate that the host doesn't exist.
The client created at this first step is expected to call the Scylla API to retrieve information about existing/available nodes and their IPs, and update this information in the DB. To avoid a situation where the client selects a non-existing IP from the pool, this PR iterates through all known hosts and creates the initial client with just a …

fix(client): validate all known_hosts on ScyllaAPI client creation

---

pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/stage.go
pkg/service/backup/worker.go
pkg/service/backup/worker_index.go
pkg/service/backup/worker_manifest.go
pkg/service/backup/worker_purge.go
pkg/service/backup/worker_schema.go
pkg/service/backup/worker_snapshot.go
pkg/service/backup/worker_upload.go

Backup: don't ignore uploadHost error

---

Makefile
pkg/rclone/aws.go

Fixes #3691 
This PR adds support for IMDSv2 instance region retrieval.
Scylla Manager Agent is using IMDS endpoint to get the instance metadata when configuring the RClone region used to write/read data from the S3 bucket.
It happens when the `s3.region` property is not configured in `scylla-manager-agent.yaml` config file.
If `s3.region` is defined, it takes precedence over the IMDS.
IMDSv2 requires to obtain the session token before calling to get the instance metadata. If the session token call fails, SM will fallback to IMDSv1 and just not include token into the request.
---

feat(aws): support for IMDSv2 on setting bucket region

---

pkg/service/repair/plan.go
pkg/service/repair/service_repair_integration_test.go

Repair: fix repair --host filtering

---

pkg/service/repair/plan.go
pkg/service/repair/service_repair_integration_test.go

https://github.com/scylladb/scylla-manager/pull/3737
---

Update 2 release 3.2.6

---

pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/client_scylla_integration_test.go
pkg/scyllaclient/model.go
pkg/service/backup/service.go
pkg/service/repair/generator.go
pkg/service/repair/master_selector.go
pkg/service/repair/model.go
pkg/service/repair/plan.go
pkg/service/repair/progress.go
pkg/service/repair/progress_integration_test.go
pkg/service/repair/repair_test.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/util/maputil/map.go

Right now, repair plan contains descriptions of all repaired rings which are stored at the keyspace level. This has two main  issues:
- unnecessary memory consumption
- it makes it difficult to move to a per table ring description required for tablets
The main goal of this PR is remove ring descriptions from plan and query them when needed during an actual repair. 
In order to achieve that, generator responsibility is passed to generator and tableGenerator. Generator is responsible for querying ring description and creating tableGenerators, which take care of repairing given table.
This introduces a lot of code refactoring, so in order to make repair logic more comprehensible I added:
- MaxRingParallel
- ShouldRepairRing
Currently, determining max parallel or if a keyspace should be …

Repair: describe ring per table and without cache

---

docs/source/sctool/partials/sctool_backup.yaml
docs/source/sctool/partials/sctool_cluster_add.yaml
docs/source/sctool/partials/sctool_cluster_update.yaml
docs/source/sctool/partials/sctool_restore.yaml

docs: regenerate views

---

pkg/service/cluster/service.go

fix(session): close client after session creation

---

pkg/command/flag/flag.go
pkg/managerclient/model.go
pkg/restapi/task.go
pkg/service/scheduler/model.go
pkg/service/scheduler/model_test.go

Fixed #3750 
Current output:
```
│ repair/2e3c9d7c-28aa-45ab-9c33-be14c1bdc5a1 │ 0 23 * * SAT; starts: 2024-08-24 23:00:00 UTC │        │ Europe/Warsaw │ 0       │ 0     │                        │                        │ NEW    │ 25 Aug 24 01:00:00 CEST │
│ repair/5954b6b0-0b17-498e-9db4-39ee25c59f9a │ 0 23 * * SAT                                  │        │ Europe/Warsaw │ 0       │ 0     │                        │                        │ NEW    │ 30 Mar 24 23:00:00 CET  │
```
---

fix(tasks): list tasks with better formatting

---

docs/source/docker/index.rst
install-dependencies.sh
testing/Makefile
testing/corrupt
testing/docker-compose-ipv4.yaml
testing/docker-compose-ipv6.yaml
testing/docker-compose.yaml

This PR switches the usage of `docker-compose` to `docker compose`.
Outdated `docker-compose` has been the reason why some gh actions jobs were failing.

Switch from docker-compose to docker compose

---

pkg/command/legacy/task/tasklist/res.yaml

Fixes https://github.com/scylladb/scylla-manager/issues/3786
---

fix(msg): update deprecate message on sctool task list

---

pkg/scyllaclient/provider.go
pkg/service/cluster/service.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/service.go
pkg/util/logutil/logutil.go

Close client and session

---

docs/source/restore/restore-schema.rst

Highlight that system_auth is a part of restore-tables procedure

---

pkg/service/cluster/service.go
pkg/service/configcache/errors.go
pkg/service/configcache/service.go
pkg/service/configcache/service_test.go

Fixes #3802 
This is just an initial stub for new cluster-config-cache service.
General description of the goal is here https://github.com/scylladb/scylla-manager/issues/3767#issue-2208639491
---

feat(config-cache): initial stub for cluster config cache service

---

docs/source/restore/index.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst

In order to display fixes/changes in SM 3.2 docs, commits need to be merged into the 3.2 branch first.

Publish 3.2 docs

---

pkg/cmd/scylla-manager/server.go
pkg/service/healthcheck/service.go

Fixes https://github.com/scylladb/scylla-manager/issues/3800
---

Remove unused methods/references to old cache in healthcheck

---

pkg/scyllaclient/client_agent.go
pkg/scyllaclient/client_agent_test.go
pkg/scyllaclient/client_scylla.go
pkg/service/repair/generator.go
pkg/service/repair/plan.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/repair/worker.go
swagger/gen/scylla/v1/client/operations/storage_service_repair_async_by_keyspace_post_parameters.go
swagger/scylla_v1.json

This PR utilizes the small_table_optimization param in repair API which allows SM to repair the whole table with just one API call. It should bring significant improvements when repairing smaller tables.
As we can't check supported API parameters on Scylla side, we need to rely on checking Scylla version.
Fixes #3642

Use small_table_optimization in repair

---

pkg/cmd/scylla-manager/root.go
pkg/cmd/scylla-manager/server.go
pkg/config/server/server.go
pkg/config/server/server_test.go
pkg/service/cluster/service.go
pkg/service/configcache/config.go
pkg/service/configcache/errors.go
pkg/service/configcache/nodeconfig.go
pkg/service/configcache/service.go
pkg/service/configcache/service_test.go
pkg/service/configcache/tlsconfig.go
pkg/service/healthcheck/service.go
pkg/service/healthcheck/service_integration_test.go

Fixes https://github.com/scylladb/scylla-manager/issues/3767
PR is ready for a review.
It consists of the following commits:
- https://github.com/scylladb/scylla-manager/pull/3816/commits/2b77a40688d8e975ed0ab8858bbe6897267c5e6c :This commit addresses the lack of an interface definition for the cluster service, which consists of CRUD operations on the cluster object.
- https://github.com/scylladb/scylla-manager/pull/3816/commits/7947bc3893ec8fb6fe738fb09c2970894fee702f: Contains the implementation of the config cache service.
- https://github.com/scylladb/scylla-manager/pull/3816/commits/303df330a45ad44d5061f81985c33cb101858b69: This commit defines the contract of the epic - to make the CQL ping and Alternator ping independent from the agent's API responsiveness.
- …

Feature branch for Config Cache Service

---

pkg/service/restore/tables_worker.go

fix(restore): post-restore repair to use max intensity and parallel

---

pkg/managerclient/model.go

Fixes #3807 
Created tasks
```
./sctool repair --cluster 46c77e6c-867b-4860-bb42-e55567561363 --interval 5d
```
Before fix:
```
➜  scylla-manager git:(3807-show-schedule-field-for-deprecated-interval) ✗ ./sctool tasks                                                                                         
Cluster:  (46c77e6c-867b-4860-bb42-e55567561363)
╭─────────────────────────────────────────────┬──────────────┬────────┬──────────────────┬─────────┬───────┬─────────────────────────┬────────────┬─────────┬─────────────────────────╮
│ Task                                        │ Schedule     │ Window │ Timezone         │ Success │ Error │ Last Success            │ Last Error │ Status  │ Next                    │
├─────────────────────────────────────────────┼──────────────┼────────┼───── …
```

fix(sctool): tasks cmd to render schedule with deprecated interval correctly

---

pkg/service/cluster/service.go

Don't query empty host on client creation

---

pkg/service/cluster/service.go
pkg/service/configcache/service.go
pkg/service/configcache/service_test.go
pkg/service/healthcheck/metrics_test.go
pkg/service/healthcheck/runner.go
pkg/service/healthcheck/service.go

Don't silence healthcheck ping errors https://github.com/scylladb/scylla-manager/issues/3845
On client creation, skip empty initial host https://github.com/scylladb/scylla-manager/issues/3849
Healthcheck to stop calling agent's for list of live nodes https://github.com/scylladb/scylla-manager/issues/3847
---

Release 3.2.8 follow up

---

pkg/scyllaclient/client_scylla.go
pkg/service/repair/controller.go
pkg/service/repair/controller_test.go
pkg/service/repair/generator.go
pkg/service/repair/intensity_handler.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/repair/worker.go

This PR introduces token ranges batching in repair jobs.
Previously, with `intensity=X`, SM would simply send X token ranges per job. As described in #3789, this approach could lead to cluster being underutilized. Batching also solves #3792, as it increases the odds of repair job consisting of similar amount of token ranges owned by any shard. 
Fixes #3789
Fixes #3792

Repair: use ranges parallelism

---

docs/source/backup/index.rst
docs/source/backup/specification.rst
docs/source/repair/index.rst
docs/source/restore/compatibility-matrix.rst
docs/source/restore/index.rst
docs/source/restore/old-restore-schema.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst
docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/res.yaml
pkg/managerclient/model.go

Docs for 3.3.0

---

pkg/scyllaclient/client_rclone_agent_integration_test.go
pkg/service/backup/worker_snapshot.go
pkg/service/repair/generator.go
pkg/service/repair/progress.go
pkg/service/repair/service_repair_integration_test.go

This PR removes flakiness from:
- `TestServiceRepairResumeAllRangesIntegration`
- `TestServiceRepairIntegration/repair temporary network outage`
- `TestRcloneStoppingTransferIntegration`
Fixes #3919

Insert repair state under mutex

---

docs/source/backup/index.rst
pkg/service/backup/export_test.go
pkg/service/backup/model.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go

Don't backup views

---

Makefile
pkg/managerclient/backup.go
pkg/rclone/rcserver/rc.go
pkg/rclone/rcserver/rchardening.go
pkg/service/backup/service.go
pkg/service/backup/service_deduplicate_integration_test.go
pkg/service/backup/service_testutils.go
pkg/service/backup/stage.go
pkg/service/backup/worker.go
pkg/service/backup/worker_deduplicate.go
pkg/service/backup/worker_upload.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/tablesdir_worker.go
pkg/sstable/sstable_naming.go
pkg/sstable/sstable_naming_test.go
testing/scylla/config/scylla.yaml

Fixes https://github.com/scylladb/scylla-manager/issues/3827
This PR adds explicit stage to the backup process - deduplication.
It follows https://docs.google.com/document/d/1EtGlF6UGNy34D_7QsnCheaukp3UwVObZU56PBdd0CQ8/edit#heading=h.jl2qbpcarwp9
It is done to mitigate the problem with current deduplication/checksum comparison which causes SM to create a checksum of every SSTable file and to compare it with the checksum from remote.
This PR changes restore of versioned snapshot as well to corrupt CRC32 files.
---

Cheksum comparison

---

pkg/scyllaclient/client_scylla.go
pkg/service/configcache/nodeconfig.go
pkg/service/configcache/service.go
pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/runner.go
pkg/service/healthcheck/service.go

Fixes #3908 
This PR adds rack and datacenter labels to `scylla-manager-healthcheck-*` metrics so that it's easier to navigate through them.
Config cache service is extended to call for `/snitch/datacenter` and `/snitch/rack` endpoints to get the information about node's dc and rack.
Scylla client is extended to support calls to `/snitch/rack`.
---

Additional labels for healtcheck metrics

---

pkg/service/backup/service_deduplicate_integration_test.go
pkg/service/backup/worker_deduplicate.go

Fixes https://github.com/scylladb/scylla-manager/issues/3959
This PR contains the following:
- includes deduplicated SSTables (by crc32) into the batch of files to delete
- updates size of deduplicated files into SkippedBytesOffset to show the progress correctly eventually
- fixes integration test of deduplication part
The problems above were find by https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/manager-master/job/sct-feature-test-backup/15/
Lack of deduplication based on crc32 could be observed on local runs (local docker setup disables UUID for generation ID).
---

Fix backup progress deduplication

---

dist/Makefile

This PR contains 2 commits:
https://github.com/scylladb/scylla-manager/commit/0813d708a66d0fc86dbba3040071edbbf475f6c5
During the automated branch creation, we mistakenly modified the dev
release to `3.4.dev` instead of `3.4.0-dev`
Fixing it
I will send a follow-up PR in Scylla-pkg to fix it on our side
https://github.com/scylladb/scylla-manager/commit/cb10ca21bd1bd653609686a258a331ce98ed260a
Today we have a complete mixup with the tags, causing an override during
builds. To avoid it, we should set a tag for each build (master or
release)
Refs: #3944
The main fix for this issue will be from the Scylla-pkg side

Makefile: Fix version and tag creation for snapshots

---

dist/Makefile

Today we have a complete mixup with the tags, causing an override during builds. To avoid it, we should set a tag for each build (master or release)
Refs: https://github.com/scylladb/scylla-manager/issues/3944
The main fix for this issue will be from Scylla-pkg side
(cherry picked from commit 0ad5692f07840928f49affc64bb37d59e7db739a)

[backport 3.3] Makefile: Set tags also during snapshot builds

---

pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/testdata/get_target/continue_false.units.json
pkg/service/restore/testdata/get_target/default_values.units.json

The dicts table is being dropped for now. See:
https://github.com/scylladb/scylla-enterprise/pull/4570 https://github.com/scylladb/scylla-enterprise/pull/4591 https://github.com/scylladb/scylla-enterprise/pull/4592
Fixes #4004

Stop testing dicts table

---

dist/.goreleaser-docker.yaml
dist/.goreleaser.yaml
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

Following the upgrade of all Jenkins nodes to Fedora40, a few configuration issues popped up

manager-build: fix configuration to match new docker version

---

pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/model.go
pkg/scyllaclient/ring_describer.go
pkg/service/backup/model.go
pkg/service/backup/service.go

This PR adds a way to filter keyspaces by:
- all keyspaces
- user keyspaces
- non local keyspaces
And uses it in backup table filtering in order to fix #3989.
Fixes #3989

Don't rely SM side calculated replication strategy when filtering backup tables

---

pkg/command/backup/cmd.go
pkg/command/backup/res.yaml
pkg/service/backup/model.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker_schema.go
pkg/service/cluster/service.go

This PR makes a several changes regarding schema backup.
They aim to increase schema backup safety by making it impossible to skip schema backup by simply not providing CQL creds (which was possible for Scylla version >= 6.0). Skipping schema backup is still possible (some users might not want to provide the CQL creds), but requires user to deliberately add the new `--skip-schema` flag. 
They also make the schema backup more robust for multi Scylla version cluster, or a cluster where SM does not have CQL access to all of the nodes.  
Fixes #4007
Fixes #3995

Improve schema backup

---

pkg/service/cluster/model.go
pkg/service/cluster/service.go

Scylla operates on host IDs or IPs, but it doesn't handle DNS names well: "N":"cluster.client","M":"HTTP retry now","operation":"SnitchDatacenterGet", "error":"agent [HTTP 500] std::invalid_argument (scylla-manager-cluster-client.scylla-manager.svc)"
That's why SM also operates mostly on IPs.
The only place where SM uses DNS name is the initial cluster contact point ('sctool cluster add --host'). So Cluster.Host should be used only for discover purposes. After that we should use its discovered IP.
Ref #4019

Don't mix DNS and IPs

---

pkg/scyllaclient/config.go
pkg/scyllaclient/hostpool.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go

Commit https://github.com/scylladb/scylla-manager/commit/5bf6b35699c0645ba8598a53516e03ba7e01383f introduced a bug that when adding cluster to SM finished with error,
cluster was still saved in SM DB, but only with the ID and known hosts fields.
That's because method validateHostsConnectivity used discoverAndSetClusterHosts
instead of discoverClusterHosts, which happened before inserting cluster to SM DB.
In case client was mistakenly initialized with "" host, getting host from the pool would panic.
This should be replaced with a simple error. This PR adds additional validation to client config,
which prohibits specifying empty host there. It also makes host pool return an error instead of panic
in case of invalid host pool response.
This PR also includes testes for mentioned issues …

Don't add cluster to SM DB before validation finishes

---

pkg/scyllaclient/config.go
pkg/scyllaclient/hostpool.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go

Fixes regression https://github.com/scylladb/scylla-enterprise/issues/4692
https://github.com/scylladb/scylla-manager/pull/4029
---

Patch fix 3.3.3

---

pkg/ping/dynamoping/dynamoping.go
pkg/ping/dynamoping/dynamoping_integration_test.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/healthcheck/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/db/db.go
testing/scylla/config/scylla.yaml

This PR does a few things:
- it enforces authentication on alternator queries (https://github.com/scylladb/scylla-enterprise/issues/4708)
- it uses creds for authenticating alternator API in pkg tests (#4032)
- it replaces alternator query ping with simple ping when authentication is enforced (#4036)
Fixes #4032
Ref https://github.com/scylladb/scylla-enterprise/issues/4708
Ref #4036

Use creds in alternator tests

---

pkg/service/repair/plan.go
pkg/service/repair/repair_test.go

Don't rely on ring replication strategy in repair

---

pkg/service/restore/helper_integration_test.go
pkg/service/restore/model.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/schema_worker.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/tables_worker.go

Target.keyspace is calculated at the beginning of each restore task run.
It is vulnerable for changes occurring during restore process, e.g.:
- restore targeting some views is started
- target.keyspace excludes restored views (checked via CQL query)
- restore is paused
- restore is resumed
- recalculated target.keyspace no longer excludes restored views
Units are calculated only once at the beginning of the restore,
so they are not vulnerable to mentioned changes and should
be used to determine which tables should be restored.
Fixes #4037

Restore: rely on run.units instead of target.keyspace

---

pkg/service/restore/restore_integration_test.go
pkg/service/restore/schema_worker.go

This is a PR aiming to fix our CI with enterprise nightly latest image.
The new `DESC SCHEMA WITH INTERNALS AND PASSWORDS` should be handled by dedicated issues:
- https://github.com/scylladb/scylla-manager/issues/3869
- https://github.com/scylladb/scylla-manager/issues/3875
Fixes #4050

Restore: skip new entities in DESC SCHEMA WITH INTERNALS

---

docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/res.yaml
pkg/scyllaclient/client_scylla.go
pkg/service/restore/batch.go
pkg/service/restore/batch_test.go
pkg/service/restore/model.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/tables_worker.go

This PR introduces the following changes to batching mechanism:
- batches contain --batch-size*node_shard_count sstables instead of just --batch-size sstables (this was the initial design in[ restore 3.1 design doc](https://docs.google.com/document/d/1ugf6XCs28c4pwKsw9Lbu_EFb6ZSgMpJ_-Usf-Q9XAP4/edit#heading=h.f7jv2tbf2ofd))
- sorts sstables by decreasing size so that batches contain sstables of more similar size (#3979)
- added a special --batch-size=0 value which results in creating batches of not limited amount of sstables, but their total size is up to 5% of expected total node workload (#4059)
Fixes #3979
Fixes #4059

Restore improvement: batch

---

v3/pkg/util/inexlist/dcfilter/dcfilter.go

Sometimes we don't have access to all dcs right away, so it's more convenient to use Check instead of Apply.
It also allows for parsing dc filters just once.
This is a ground work for #4049.

Allow for creating stand-alone dc filter

---

docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/cmd.go
pkg/command/restore/res.yaml
pkg/service/backup/service_backup_integration_test.go
pkg/service/restore/model.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/tables_worker.go

This PR adds new boolean restore flag `--allow-compaction` (false by default).
When it's set to false, SM disables auto compactions on restored tables for the time of the restore and enables them back when its done.
Fixes #3953

Restore improvement: compaction

---

v3/swagger/agent.json
v3/swagger/gen/agent/client/operations/core_transfers_parameters.go
v3/swagger/gen/agent/models/copy_paths_options.go
v3/swagger/gen/agent/models/move_or_copy_file_options.go

This PR is a ground work required for #4054 required because it needs to extend rclone API.

Extend rclone API with bandwidth limit/transfers on upload/download

---

docs/source/sctool/partials/sctool_restore.yaml
docs/source/sctool/partials/sctool_restore_update.yaml
pkg/command/restore/cmd.go
pkg/command/restore/res.yaml
pkg/scyllaclient/client_rclone.go
pkg/scyllaclient/client_rclone_agent_integration_test.go
pkg/scyllaclient/client_rclone_integration_test.go
pkg/service/backup/backup.go
pkg/service/backup/backup_test.go
pkg/service/backup/backupspec/dclimit.go
pkg/service/backup/backupspec/location.go
pkg/service/backup/model.go
pkg/service/backup/parallel.go
pkg/service/backup/parallel_test.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/service_deduplicate_integration_test.go
pkg/service/backup/worker_deduplicate.go
pkg/service/backup/worker_upload.go
pkg/service/restore/model.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/tables_worker.go
pkg/service/restore/tablesdir_worker.go
pkg/service/restore/worker.go

This PR adds a way to control rate limit in the context of restore via new `--rate-limit` restore flag with default value 0 - meaning no rate limit at all.
It borrows rate limit syntax from backup pkg for consistency - meaning that it's possible to specify rate limit per dc.
Fixes #3947

Restore improvement: rate limit

---

pkg/service/backup/backupspec/location.go
pkg/service/restore/batch.go
pkg/service/restore/batch_test.go
pkg/service/restore/index.go
pkg/service/restore/model.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/tables_worker.go

This PR adds 2 changes related to work orchestration during download and LAS stage.
1. If node failed to restore a batch, the batch is returned to the batch dispatcher and can be retried by other nodes
2. If node failed to restore a batch, the node can still try to restore other batches, but from different dcs from backup manifest
After batch failed to be restored, SM cleans the upload dir, so that there are no left overs there.
Those changes aim to make restore more robust, and should help with #3871.
Moreover, this PR also refactors general areas connected to batching:
- added lots of comments explaining batching mechanism
- restore workload structure is now flattened and not modified by the batching mechanism - a new workload progress structure has been added to represent current state …

Restore improvement: batch retry

---

pkg/metrics/restore.go
pkg/service/restore/progress.go
pkg/service/restore/tables_worker.go
pkg/service/restore/tablesdir_worker.go

This PR add new restore metrics:
- `downloaded_bytes` (downloaded bytes) labeled by `cluster`, `location`, `host`
- `download_duration` (download duration in ms) labeled by `cluster`, `location`, `host`
-  `streamed_bytes` (load&streamed bytes) labeled by `cluster`, `host`
- `stream_duration` (load&stream duration in ms) labeled by `cluster`, `host`
They can be easily used to calculate download/stream bandwidth.
Ref #4042

Restore: add bandwidth metrics

---

v3/pkg/managerclient/model.go

Previously all run/task properties of post-restore repair progress were taken directly from the restore progress.
This included things like start/end time, properties, status, cause and others. It resulted in misleading progress display. This commit fixes that by deliberately leaving out, inheriting, or setting interesting repair progress fields.
Fixes #4046

Managerclient: improve post-restore repair progress display

---

docs/source/restore/index.rst

This commit adds description of how to observe restore speed, and how to configure restore parameters in order to restore as fast as possible.
Fixes #3946

Docs: document restore speed and observability

---

docs/source/sctool/partials/sctool_stop.yaml
pkg/command/stop/res.yaml

Clarify details about sctool stop --disable

---

.github/cfg/integration-test-cfg.yaml
.github/workflows/integration-tests-2024.1.12-IPV4.yaml
.github/workflows/integration-tests-2024.1.12-IPV6.yaml
.github/workflows/integration-tests-6.2.0-IPV4-tablets.yaml
.github/workflows/integration-tests-6.2.0-IPV4.yaml
.github/workflows/integration-tests-6.2.0-IPV6-tablets.yaml
README.md

This PR also bumps other patch versions.

Test Scylla 6.2

---

pkg/cmd/scylla-manager/server.go
pkg/scyllaclient/client_scylla.go
pkg/scyllaclient/retry_integration_test.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go
pkg/service/healthcheck/service_integration_test.go
pkg/testutils/exec.go
pkg/testutils/netwait_integration_test.go

Fixes #4074
This PR makes the cluster hosts discovery more robust, as when the cluster.host is DOWN,
it probes all other hosts in parallel and returns response from the fastest one.
Additionally, this PR makes the call to cluster config cache async on updating cluster.
---

Parallelized cluster hosts discovering + async config cache update

---

pkg/rclone/rcserver/rcconfigguard.go
pkg/scyllaclient/client_rclone.go
pkg/service/backup/worker_deduplicate.go
pkg/service/backup/worker_upload.go

This PR fixes the way in which `configguard` checked if bandwidth limit should be updated.
Previously it was updating bandwidth limit with each Rclone call, now it updates it only when it's changed.
This PR also removes unnecessary usages of `RcloneSetBandwidthLimit`, as handling bandwidth limit should be done by specific Rclone calls.
Fixes #4119

Rclone: don't rely on cached bandwidth limit in configguard

---

docs/source/restore/index.rst

This documents how to prevent interference between restore and backup/repair tasks prior changes made in #4122 
Fixes: #3742
---

docs: how to avoid restore and backup/repair tasks interference

---

docs/source/restore/index.rst
docs/source/sctool/partials/sctool_repair.yaml
docs/source/sctool/partials/sctool_repair_update.yaml

This extends restore procedure docs with how to avoid conflicts between restore and backup/repair tasks in a cluster.
Fixes: #3742
---

docs: adds info about restore and backup/repair tasks interference

---

pkg/cloudmeta/aws.go
pkg/cloudmeta/metadata.go
pkg/cloudmeta/metadata_test.go

This adds basic interface and models to work with different cloud metadata providers and also adds implementation for aws metadata provider. 
This package will be used in order to extend backup manifest with additional information. 
This changes has been manually tested with the help of https://github.com/aws/amazon-ec2-metadata-mock container. 
Fixes: #4127 
---

feat: adds cloudmeta package with AWS provider

---

pkg/cmd/scylla-manager/server.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/configcache/service.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/service.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/testconfig/testconfig.go
pkg/testutils/testhelper/helper.go

This is the first general step toward fixing #3892.
It allows for accessing config cache service from other services.
Actually using config cache service will be implemented in separate PRs.
Ref #3892

Let other services use config cache

---

pkg/cloudmeta/metadata_test.go

This increases delay between 'fast' and 'slow' providers in metadata unit tests to reduce chance of failure.
Fixes: #4173
---

fix(tests): increases delays in `pkg/cloudmeta` unit tests.

---

pkg/cloudmeta/gcp.go
pkg/cloudmeta/gcp_test.go
pkg/cloudmeta/metadata.go

This adds gcp metadata provider support to cloudmeta package.
This changes has been manually tested on gcp node in lab env.
Fixes: #4128
P.S. retries are handled by gcp sdk, here is the note from documentation of `GetWithContext(...)`method.
```
Without an extra deadline in the context this call can take in the worst case, with internal backoff retries, up to 15 seconds (e.g. when server is responding slowly). Pass context with additional timeouts when needed.
```
---

feat: adds gcp metadata provider support to cloudmeta package

---

v3/swagger/agent.json
v3/swagger/gen/agent/models/node_info.go

This extends `/node_info` agent response with `storage_size` - total disk size in bytes. It's needed for the backup manifest and should be calculated on the agent side.
Refs: #4130 
p.s. I've realized that exposing `DataDirectory` is not enough, because `storage_size` can be calculated only on agent side, but backup manifest is created on the SM side.
---

feat(swagger): extends sm agent `/node_info` with `storage_size`.

---

pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/runner.go

Commits a75df89c and 3cdd20dc added and started setting new labels (dc/rack) in healthcheck metrics.
Unfortunately, those labels weren't taken into consideration when removing metrics of removed clusters/nodes:
https://github.com/scylladb/scylla-manager/blob/cafa851a39fc4d1238b4d2827f11058dd81158a1/pkg/service/healthcheck/runner.go#L116-L121
This resulted in not removing those metrics until SM restart.
This commit fixes this issue and brings a small refactor to the way in which healthcheck labels are applied, so that it's more difficult to make such mistake in the future.
Fixes #4017

Healthcheck: correctly label nodes removed from metrics

---

pkg/service/healthcheck/metrics.go
pkg/service/healthcheck/runner.go

This PR adds a fix for #4017 into the 3.4.1 release.

Add a fix for #4017 into the 3.4.1 release

---

pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/service_deduplicate_integration_test.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/version.go

Some tests were missing the `Integration` suffix in their names.
This resulted in not including them in the `make pkg-integration-test` command used when running tests on gh actions.
E.g. `TestBackupViews` was skipped in https://github.com/scylladb/scylla-manager/actions/runs/12372495884/job/34530829780.

Add missing 'Integration' suffix to tests

---

pkg/scyllaclient/client_ping.go

That's how the majority of the SM logs look like:
<details>
<Summary> example </Summary>
```
Jan 04 13:51:10 scylla-admin-01-p scylla-manager[1424033]: {"L":"INFO","T":"2025-01-04T13:51:10.004+0600","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"0ced091a-cc6a-4d2d-8f4f-14e19ae4a10c","_trace_id":"kCNEUDYBTsChj6NUUh3fYQ"}
Jan 04 13:51:10 scylla-admin-01-p scylla-manager[1424033]: {"L":"INFO","T":"2025-01-04T13:51:10.017+0600","N":"cluster.client","M":"Measuring datacenter latencies","dcs":["ST"],"_trace_id":"kCNEUDYBTsChj6NUUh3fYQ"}
Jan 04 13:51:10 scylla-admin-01-p scylla-manager[1424033]: {"L":"INFO","T":"2025-01-04T13:51:10.866+0600","N":"cluster","M":"Creating new Scylla HTTP client","cluster_id":"0ced091a-cc6a-4d2d-8f4f-14e19ae4a10c","_trace_id":"2-gk21DpRt2dBQ8MjZERH …
```

Reduce info to debug on closest DC

---

pkg/scyllaclient/client_agent.go
pkg/scyllaclient/client_agent_test.go

It turns out that Scylla 2024.2 does not expose this API. For now, it's not know which enterprise release will contain it.
Luckily for us, this was present only on SM master, so no need for backporting it to any release.
Fixes #4183

Don't query raft read barrier API on Scylla 2024.2

---

pkg/service/restore/service_restore_integration_test.go

When new restore task is executed, it should have its own task ID and run ID, but the cluster ID should remain the same. This commit fixes an autofill typo from the past. It was discovered because it affected the config cache service.

Restore test: keep single cluster ID for many restores

---

pkg/service/configcache/service.go
pkg/service/configcache/service_test.go

Otherwise, we panic inside updateSingle method.
This commit also contains a small test for
testing this behavior.

Configcache: return on error in ForceUpdateCluster

---

pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/hrt.go
testing/scylla/config/scylla.yaml

This PR makes SM tests run against UUID SSTables.
It adds a method for creating artificial integer SSTables that is used for testing versioned backup/restore behavior.
Fixes #4182

Testing: use UUID based SSTables for testing

---

v3/swagger/gen/scylla-manager/models/restore_host_progress.go
v3/swagger/gen/scylla-manager/models/restore_keyspace_progress.go
v3/swagger/gen/scylla-manager/models/restore_progress.go
v3/swagger/gen/scylla-manager/models/restore_table_progress.go
v3/swagger/scylla-manager.json

In overall/keyspace/table progress we were reporting both downloaded and restored bytes. There are two problems with it:
1. Users does not really care for the distinction between downloaded and restored bytes - they just want to know the amount of bytes that have been successfully restored.
2. With new native Scylla API restore, we no longer separate restoration into download/load&stream stages.
That's why we should move towards reporting just the amount of successfully restored bytes, and not keep on adding another fields to our API for each new type of restore.
This commit:
- Adds restored_bytes/duration to host progress, since it was lacking there. It does not deprecate the downloaded/streamed fields because they were just added in the previous minor release, so that would be …

Swagger: scylla-manager, move towards just restored bytes

---

v3/pkg/managerclient/tasks.go

This adds a new task type for 1-1 vnode restore.
As managerclient is a separate go module, changes into it should be merged first. 
~~Fixes 4200~~
Part1 of #4200 
see Part2 - #4221 
---

feat(managerclient): adds new task type - 1_1_restore

---

dist/.goreleaser-docker.yaml
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

To achieve OpenShift certification for the Scylla-Operator, our Scylla Manager container images must be based on Red Hat's UBI images.
Fixes: https://github.com/scylladb/scylla-manager/issues/4242

feat(manager docker) switch to be based on ubi9-minimal

---

pkg/cmd/scylla-manager/server.go

Fixes #4249 
This PR "unplugs" background config-cache update from the API call context.
Before change (context cancelled):
```
➜  scylla-manager git:(kk/4249-update-config-cache-in-separation-from-api-call) ✗ ./sctool.dev cluster update --cluster 6bb4f1d2-8ab7-4ed8-894b-767d52b1664e --username cassandra --password cassandra
04:49:06.975    INFO    http    PUT /api/v1/cluster/6bb4f1d2-8ab7-4ed8-894b-767d52b1664e        {"from": "192.168.100.1:41228", "status": 200, "bytes": 223, "duration": "61ms", "_trace_id": "DzcJULtaRPu77hSBdQM8zw"}
04:49:06.975    INFO    cluster Creating new Scylla HTTP client {"cluster_id": "6bb4f1d2-8ab7-4ed8-894b-767d52b1664e", "_trace_id": "DzcJULtaRPu77hSBdQM8zw"}
04:49:06.976    ERROR   cluster Couldn't discover hosts using stored coordinator host, proceeding …
```

fix(cluster update): separate cache update context from API call

---

.github/cfg/integration-test-core.yaml
.github/workflows/integration-tests-2023.1.11-IPV4-raftschema.yaml
.github/workflows/integration-tests-2023.1.11-IPV4.yaml
.github/workflows/integration-tests-2023.1.11-IPV6-raftschema.yaml
.github/workflows/integration-tests-2024.1.12-IPV4.yaml
.github/workflows/integration-tests-2024.1.12-IPV6.yaml
.github/workflows/integration-tests-6.2.0-IPV4-tablets.yaml
.github/workflows/integration-tests-6.2.0-IPV4.yaml
.github/workflows/integration-tests-6.2.0-IPV6-tablets-nossl.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4-tablets-nossl.yaml
.github/workflows/integration-tests-latest-enterprise-IPV4.yaml
Makefile
pkg/service/one2onerestore/helpers_integration_test.go
pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/service.go
pkg/service/one2onerestore/service_integration_test.go
pkg/service/one2onerestore/worker_tables.go
pkg/service/one2onerestore/worker_tables_test.go
pkg/service/one2onerestore/worker_validate_integration_test.go

This adds copy data stage for the 1-1-restore with simple integration test (create backup, truncate tables, restore).
Data is copied by each node, table by table and after copy data dir job loadSStables is called.
Refs: #4202 #4203 
P.S. For now I've added 1-1-restore integration test under  `Test other, smaller packages` check as it small enough (run takes about 30s) and doesn't cover a lot of use cases.
Also this pr includes full support for `--keyspace` parameter (meaning you can filter tabels, use `!` and etc), but it will be changed in separate PR accordingly to #4253 
---

feat(1-1-restore): adds copy data stage + loadSStables call

---

v3/swagger/gen/scylla/v1/client/operations/storage_service_tablets_repair_post_parameters.go
v3/swagger/gen/scylla/v1/client/operations/storage_service_tablets_repair_post_responses.go
v3/swagger/scylla_v1.json

This PR adds new 'await_completion' query param
introduced in https://github.com/scylladb/scylladb/pull/22436
and updates response to task manager task ID
as per https://github.com/scylladb/scylladb/pull/22436#issuecomment-2614704691.

Swagger: scylla, update tablet repair API

---

pkg/service/repair/helper_integration_test.go
pkg/service/repair/service_repair_integration_test.go

This is a ground work for introducing new tablet repair API into repair service tests.
It mainly:
- separates interceptor request parsing from the test code, so that it's easier to extend it with new tablet repair endpoints
- tries not to rely on tablet table ranges count, as the new tablet repair API will repair an entire table with a single call
- improves vnode/tablet keyspace creation

Refactor repair tests

---

pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/service.go
pkg/service/one2onerestore/service_integration_test.go
pkg/service/one2onerestore/worker.go
pkg/service/one2onerestore/worker_tables.go
pkg/service/one2onerestore/worker_views.go
pkg/service/one2onerestore/worker_views_test.go

This adds support for restoring views in 1-1-restore. Views should be dropped before copy data stage and then re-created to avoid data inconsistency between base table and view.
Integration test extended with MaterializedView. 
Refs: #4252
---

feat(1-1-restore): adds support for views

---

go.mod
go.sum
pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/model_test.go
pkg/service/one2onerestore/service.go
pkg/service/one2onerestore/worker.go
vendor/modules.txt

This reduces functionality of `--keyspace` parameter to support only:
- keyspace level filtering. Table level filtering (system.table_name) is forbidden.
- only include filtering. Excluding(!) is forbidden.
- wildcards (\*) are forbidden. The only exception is when the only filter that is provided is a single character (*), meaning that all keyspaces should be included into restore process - it's a default value if `--keyspace` is not provided.
Refs: #4253
---

feat(1-1-restore): reduces --keyspace param features to keyspace level filtering only

---

pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/service.go
pkg/service/one2onerestore/service_integration_test.go
pkg/service/one2onerestore/worker.go
pkg/service/one2onerestore/worker_tgc.go
pkg/service/one2onerestore/worker_views.go

This sets tombstone_gc mode to 'repair' to avoid data resurrection.
If tables mode is already 'repair', 'disabled' or 'immediate', then it won't be changed.
I'm not 100% sure if it's a safe to leave 'immediate' unchanged, but from the docs seems ok. 
P.S.
Also this adds skipping of local system tables - the same way we have in
regular restore service.
P.S.2 : )
I think it may turn out that we need to set tombstone gc mode to 'repair' for views as well. I've created https://github.com/scylladb/scylla-manager/issues/4261 to investigate this.
---

feat(1-1-restore): sets tombstone_gc mode to repair 

---

pkg/scyllaclient/client_agent.go
pkg/scyllaclient/client_scylla.go
pkg/service/repair/generator.go
pkg/service/repair/helper_integration_test.go
pkg/service/repair/plan.go
pkg/service/repair/service.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/repair/worker.go
pkg/service/restore/service_restore_integration_test.go

This PR adds support for tablet repair API in Scylla 2025.1.0:
- for Scylla < 2025.1.0 - repairing tablet keyspaces stops tablet load balancing and uses old repair API
- for Scylla == 2025.1.0 - SM never stops tablet load balancing, it uses tablet repair API for repairing entire tablet table and old repair API for repairing partial tablet table
- for Scylla >= 2025.1.1 - SM never stops tablet load balancing and always uses tablet repair API which is extended with host filtering capabilities (not yet implemented)
See #4273 for the decision process about not stopping tablet load balancing.
Fixes #4188

Tablet repair API

---

dist/.goreleaser-docker.yaml
dist/Makefile
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

update latest to actual latest tag available by running docker pull scylladb/scylla-manager:latest
Fixes:scylladb#4250

goreleaser: Update latest tag on docker hub to actual latest

---

docs/source/backup/examples.rst

Fix location flag syntax in backup examples

---

pkg/scyllaclient/client_scylla.go
pkg/service/backup/worker_scylla_upload.go
pkg/service/backup/worker_upload.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/tables_worker.go
pkg/service/restore/worker_scylla_restore.go

Set Scylla user task TTL when using native Scylla API

---

LICENSE
README.md
docs/source/index.rst

It's worth to note that the old SM licenses are still available under:
- older release branches
- https://www.scylladb.com/2024/12/18/why-were-moving-to-a-source-available-license/
- https://www.scylladb.com/scylla-source-available-license/
Fixes #4229

Move to AGPL

---

dist/.goreleaser-docker.yaml
dist/docker/scylla-manager-agent.dockerfile
dist/docker/scylla-manager.dockerfile

To make docker image ready for Red Hat OpenShift Software Certification,
we need to fix following requirements which mentioned on the document of
the certification:
- HasRequiredLabel: we need to define labels which describes the image
- HasLicense: we need to add license file to /licenses
(described at:
https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html/red_hat_openstack_certification_policy_guide/index)
With this patch, openshift-preflight will returns following result:
"Preflight result: PASSED"
related #4242

docker: fix Docker image to pass OpenShift Certification

---

docs/source/compatibility-matrix.rst

It might encourage users to keep on using OSS
Scylla with SM that moved to AGPL and does not
have the 5 nodes limitation.
Duplicate of #4338 for `branch-3.5`.

Don't support Scylla 6.2 with SM 3.5 (branch-3.5)

---

docs/source/compatibility-matrix.rst

It might encourage users to keep on using OSS
Scylla with SM that moved to AGPL and does not
have the 5 nodes limitation.
cc: @tzach

Don't support Scylla 6.2 with SM 3.5

---

pkg/service/restore/helper_integration_test.go
pkg/service/restore/restore_integration_test.go

Client side retries shouldn't be required for restore tests.
On the other hand, they might hide some issues, so it's better
to disable it by default.

Remove restore test retries

---

docs/source/health-check.rst
pkg/ping/cqlping/cqlping.go

Very similar to changes we've recently made in the drivers (see scylladb/java-driver#282 and scylladb/python-driver#418 , the query to system.local should be with the WHERE close to prevent a scan and just issue a local query.
Fixes: https://github.com/scylladb/scylla-manager/issues/4329
---

cqlping: perform a query and not a scan

---

v3/pkg/managerclient/client.go
v3/pkg/managerclient/go.mod
v3/pkg/managerclient/go.sum
v3/pkg/managerclient/model.go
v3/pkg/managerclient/model_test.go
v3/pkg/managerclient/testdata/1.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/1.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/2.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/2.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/3.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/3.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/4.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/4.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/5.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/5.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/6.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/6.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/testdata/7.1_1_restore_run_progress.json
v3/pkg/managerclient/testdata/7.1_1_restore_run_progress.json.golden
v3/pkg/managerclient/utils.go

This adds 1-1-restore progress to managerclient and also introduces
text rending of the progress model.
Here is a few examples of how rendered progress will look like:
```
Run:		task_run_id
Status:		DONE
Start time:	01 Jan 25 10:00:00 CET
End time:	01 Jan 25 11:00:00 CET
Duration:	1h0m0s
Progress: 
Tables: 100%
Views:  100%
```
With details:
```
Run:		task_run_id
Status:		DONE
Start time:	01 Jan 25 10:00:00 CET
End time:	01 Jan 25 11:00:00 CET
Duration:	1h0m0s
Progress: 
╭───────────┬────────┬───────┬──────────┬──────────┬─────────────╮
│ Keyspace  │ Table  │ Size  │ Restored │ Duration │ Status      │
├───────────┼────────┼───────┼──────────┼──────────┼─────────────┤
│ keyspace1 │ table1 │ 1000B │ 1000B    │ 30m0s    │ done        │
│ keyspace1 │ table2 │ 1000B │ 500B     │ 1h0m0s   │ …
```

feat(1-1-restore): add progress and rendering to v3/managerclient module

---

pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/progress_integration_test.go
pkg/service/one2onerestore/service_integration_test.go
pkg/service/one2onerestore/worker.go
pkg/service/one2onerestore/worker_test.go

This adds additional validation to check that there are no tablet based keyspaces in the cluster, because 1-1-restore can work only with vnodes.
Refs: #4254
---

feat(1-1-restore): fail validation if tablet-based keyspaces are present

---

pkg/service/one2onerestore/worker.go
pkg/service/one2onerestore/worker_tables.go

This disables auto compaction during 1-1-restore for the download and refresh period and then re-enables it afterwards.
Refs: #4369
---

feat(1-1-restore): disable auto compaction during download&refresh

---

pkg/cmd/scylla-manager/server.go
pkg/metrics/one2onerestore.go
pkg/service/one2onerestore/helpers_integration_test.go
pkg/service/one2onerestore/progress.go
pkg/service/one2onerestore/progress_integration_test.go
pkg/service/one2onerestore/service.go
pkg/service/one2onerestore/worker.go
pkg/service/one2onerestore/worker_tables.go
pkg/service/one2onerestore/worker_validate_integration_test.go
pkg/service/one2onerestore/worker_views.go
pkg/service/one2onerestore/worker_views_test.go

This adds following metrics to 1-1-restore:
- download_remaining_bytes
- state: downloading (0), loading (1), done (2), error (3) 
- view_build_status: unknown (0), started (1), success (2), error (3)
Refs: #4204
---

feat(1-1-restore): add metrics to 1-1-restore

---

go.mod
go.sum
pkg/service/one2onerestore/stats.go
pkg/service/one2onerestore/stats_test.go
pkg/service/one2onerestore/worker_tables.go
vendor/github.com/scylladb/scylla-manager/v3/pkg/util/LICENSE
vendor/github.com/scylladb/scylla-manager/v3/pkg/util/sizesuffix/sizesuffix.go
vendor/modules.txt

This introduces restoreStats struct which can be used to collect various statistics during 1-1-restore run.
For now main use case is to provide avg download bandwidth in the same format as regular restore task progress, so SCT (e2e tests) can use it to compare regular and 1-1 restores.
Also this adds bandwidth per table in bytes/ms to logs which can be useful for investigative purposes.
Here is how appropriate log will looks like: 
```text
11:18:09.464    INFO    one2onerestore  Restore stats   {"bandwidth_per_shard": "10.540KiB/s/shard", "_trace_id": "SPYCOXJSSP6bxztF_Rh2IQ"}
```
Refs: #4373
---

feat(1-1-restore): add download bandwidth to logs

---

docs/source/sctool/partials/sctool_restore_1-1-restore.yaml
docs/source/sctool/partials/sctool_restore_1-1-restore_update.yaml
pkg/command/one2onerestore/cmd.go
pkg/command/one2onerestore/res.yaml
pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/worker.go

This adds support of unpin-agent-cpu flag to 1-1-restore command.
Unpinning agent CPU should help with agent download speed.
Refs: https://github.com/scylladb/scylla-manager/issues/4375
---

feat(1-1-restore): add unpin-agent-cpu flag 

---

v3/swagger/gen/scylla/v1/client/operations/storage_service_backup_post_parameters.go
v3/swagger/scylla_v1.json

Needed for #4410.
Swagger schema taken from [here](https://github.com/scylladb/scylladb/blob/7fef2c4f619022cd6a08bea6fe79699efdcfbd62/api/api-doc/storage_service.json#L817-L824).

swagger/scylla: add move_files param to /storage_service/backup

---

docs/source/backup/index.rst
docs/source/backup/specification.rst
docs/source/repair/index.rst
docs/source/restore/examples.rst
docs/source/restore/old-restore-schema.rst
docs/source/restore/restore-schema.rst
docs/source/restore/restore-tables.rst

Scylla license change also resulted in a new place for Source Available Scylla docs. We should link to its docs instead of the older Open Source or Enterprise docs.
Fixes #4416

docs: link to new scylla docs

---

pkg/scyllaclient/client_agent.go
pkg/scyllaclient/client_agent_test.go

When writing this check, there was no enterprise release which exposed read barrier API. It needs to be updated.

Use Scylla read barrier API for Scylla 2025.1

---

dist/etc/scylla-manager.yaml
pkg/config/server/server_test.go
pkg/config/server/testdata/scylla-manager.yaml
pkg/scyllaclient/client_scylla.go
pkg/service/repair/config.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/repair/worker.go

This PR removes SM side timeouts on long API calls such as:
- repair status for vnodes (still possible to configure via `scylla-manager.yaml`)
- load&stream
It also removes unused repair config fields from `scylla-manager.yaml`.
Fixes #4419

Don't timeout on long API calls

---

pkg/service/one2onerestore/model.go
pkg/service/one2onerestore/progress.go
pkg/service/one2onerestore/testdata/AggregateProgress/Only_views_progress.golden.json
pkg/service/one2onerestore/testdata/AggregateProgress/Tables_and_views_progress,_status_done.golden.json
pkg/service/one2onerestore/testdata/AggregateProgress/Tables_and_views_progress,_status_failed.golden.json
pkg/service/one2onerestore/testdata/AggregateProgress/Tables_and_views_progress,_status_in_progress.golden.json
pkg/service/one2onerestore/testdata/AggregateProgress/Tables_and_views_progress,_status_mixed.golden.json
pkg/service/one2onerestore/testdata/AggregateProgress/Tables_and_views_progress,_status_not_started.golden.json

This fixes several small issues in 1-1-restore progress aggregation:
1. Uniqueness of views was checked by keyspace + table name
2. Progress model had the wrong json tag for ViewType
---

fix(1-1-restore): fix 1-1-restore progress aggregation

---

pkg/metrics/one2onerestore.go
pkg/service/one2onerestore/progress.go
pkg/service/one2onerestore/stats.go
pkg/service/one2onerestore/stats_test.go
pkg/service/one2onerestore/worker_tables.go

This adds one2onerestore_progress metric that will show percent of downloaded bytes from 0 to 100%.
Considering that loadSSTables calls should be quick and the most amount of time 1-1-restore will spend downloading files from s3 it's fair to say that this metric indicates global 1-1-restore process progress. 
---

feat(1-1-restore): add one2onerestore_progress metric

---

.github/cfg/integration-test-cfg.yaml
.github/cfg/integration-test-core.yaml
.github/cfg/main.go
.github/workflows/integration-tests-2024.1.15-IPV4.yaml
.github/workflows/integration-tests-2024.1.15-IPV6-raftschema-nossl.yaml
.github/workflows/integration-tests-2024.2.7-IPV4-nossl.yaml
.github/workflows/integration-tests-2024.2.7-IPV6.yaml
.github/workflows/integration-tests-2025.1.0-IPV4.yaml
.github/workflows/integration-tests-2025.1.0-IPV6-tablets-nossl.yaml
.github/workflows/integration-tests-latest-IPV4-native.yaml
.github/workflows/integration-tests-latest-IPV6-tablets-nossl-rclone.yaml
Makefile
README.md
pkg/service/backup/model.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/worker.go
pkg/service/backup/worker_upload.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/testutils/testconfig/testconfig.go

This PR adds `-backup-method` to test flags and uses it in backup and restore integration tests to choose the default backup `--method`. This allows us to test both native and rclone backups without relying on the native backup incompatibility with IPV6 env and the default `--method=auto`.
Refs #4437
Fixes #4393

Set backup method in CI

---

pkg/scheduler/activation.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

Previous behavior for a long run:
```
Cron activation: |-A-------A-------A------ ...
Task execution:  |-[EEEEEEEE]------[EEE]-- ...
```
Fixed behavior:
```
Cron activation: |-A-------A-------A------ ...
Task execution:  |-[EEEEEEEE][EEE]-[EEE]-- ...
```
Previous behavior for retries:
```
Cron activation:      |-A-------A-------A----- ...
Task execution/retry: |-[E]-[R]-[R]-----[EE]-- ...
```
Fixed behavior:
```
Cron activation:      |-A-------A-------A----- ...
Task execution/retry: |-[E]-[R]-[R][EE]-[EE]-- ...
```
Fixes #4309

Scheduler: don't skip cron activations

---

go.mod
go.sum
pkg/scyllaclient/client_scylla.go
pkg/service/one2onerestore/worker_tables.go
pkg/service/restore/schema_worker.go
pkg/service/restore/tablesdir_worker.go
v3/pkg/managerclient/client.go
v3/pkg/managerclient/model.go
vendor/github.com/scylladb/scylla-manager/v3/swagger/gen/scylla/v1/client/operations/storage_service_sstables_by_keyspace_post_parameters.go
vendor/modules.txt

This adds following features/commits from the 1-1-restore-feature-branch to master:
* updates main module to use the laster swagger module 
* expose and use skip_cleanup && skip_reshape parameters
* managerclient: render cluster suspend details
There will be one more PR (final) with just two commits: 
* update main module with the latest managerclient module 
* sctool: render cluster suspend details
---

[1-1-restore] Next batch of commits to master (4)

---

go.mod
go.sum
pkg/command/status/cmd.go
vendor/github.com/scylladb/scylla-manager/v3/pkg/managerclient/client.go
vendor/github.com/scylladb/scylla-manager/v3/pkg/managerclient/model.go
vendor/modules.txt

This adds final batch of commits from 1-1-restore-feature-branch to master: 
* update managerclient dependency to the latest version
* sctool: render suspend details table 
---

[1-1-restore] Final batch of commits to master

---

docs/source/backup/specification.rst

This updates backup specification documentation with details regarding new fields in the manifest file.
Fixes: #4131
---

chore(docs): update backup specification page

---

pkg/metrics/restore.go
pkg/scyllaclient/client_agent.go
pkg/service/restore/batch.go
pkg/service/restore/batch_test.go
pkg/service/restore/helper_integration_test.go
pkg/service/restore/index.go
pkg/service/restore/progress.go
pkg/service/restore/progress_test.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/service.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/tables_worker.go
pkg/service/restore/tablesdir_worker.go
pkg/service/restore/testdata/AggregateProgress/mixed_API_full_tab1_full_tab2.golden.json
pkg/service/restore/testdata/AggregateProgress/mixed_API_full_tab1_partial_tab2.golden.json
pkg/service/restore/testdata/AggregateProgress/scylla_API_full_tab1_partial_tab2.golden.json
pkg/service/restore/testdata/AggregateProgress/scylla_API_partial_tab1_partial_tab2.golden.json
pkg/service/restore/worker.go
pkg/service/restore/worker_scylla_restore.go

This PR if a followup to #4381 which contains remaining changes from `ml/scylla-api-2`.
It introduces a replacement for rclone copypaths API in a form of native restore Scylla API. 
Fixes #4144
Fixes #4137
Fixes #4142
Fixes #4158
Fixes #4385
Fixes #4194

Merge native restore support

---

pkg/service/healthcheck/service.go

- this check is not performed for corresponding pingCQL method
- it is validated that NodeInfo is not nil in other parts of the code
- error from failed check is a wrapped nil - so it is also nil (would be problematic if this check ever failed)

Healthcheck: remove confusing nil NodeInfo check from pingAlternator

---

pkg/rclone/providers.go

This reverts part of the a64bf059 commit which moved provider options filling to the top of agent root command in order to utilize filled options in node info handler.
The problem is that it also removed provider options filling from functions registering providers. It worked fine for the agent root command, but it resulted in not filling provider options in other sm-agent commands (e.g. 'scylla-manager-agent check-location').

Always fill options on provider registration

---

v3/swagger/gen/scylla-manager/client/operations/delete_cluster_cluster_id_parameters.go
v3/swagger/gen/scylla-manager/models/cluster.go
v3/swagger/scylla-manager.json

Alternator credentials need to be handled similarly to CQL credentials.
User should be able to add them with `sctool cluster <add|update> --alternator-access-key-id  --alternator-secret-access-key`.
User should be able to delete them with `sctool cluster update --delete-alternator-credentials`.
User should be able to check if the credentials are set with `sctool status`.
Refs #4510

Swagger: scylla-manager, add definitions for alternator creds

---

backupspec/go.mod
backupspec/go.sum
backupspec/paths.go
backupspec/paths_test.go
backupspec/schema.go

This PR extends `backupspec` with alternator schema format and paths needed for backing up alternator schema.
Refs #4528
Refs #4512

Backupspec: add alternator schema format and path

---

pkg/service/backup/service.go
pkg/service/backup/validation.go
pkg/service/restore/service.go

Even though SM does not handle topology changes during backup/restore/repair tasks, we still should respect those which finish right before task is executed, but before config cache is updated.
Fixes #4524

Force update config cache before reading it

---

pkg/restapi/cluster.go
pkg/restapi/cluster_test.go
pkg/restapi/mock_clusterservice_test.go
pkg/restapi/services.go
pkg/secrets/alternatorcreds.go
pkg/service/cluster/model.go
pkg/service/cluster/service.go
pkg/service/cluster/service_integration_test.go

Alternator credentials need to be handled similarly to CQL credentials. User should be able to add them with `POST /clusters/`. User should be able to delete them with `DELETE /cluster/<cluster ID>/`. User should be able to check if the credentials are set with `GET /clusters/`.
Refs #4510

Handle alternator creds

---

docs/source/sctool/partials/sctool_cluster_add.yaml
docs/source/sctool/partials/sctool_cluster_update.yaml
go.mod
go.sum
pkg/command/cluster/clusteradd/cmd.go
pkg/command/cluster/clusteradd/cmd_integration_api_test.go
pkg/command/cluster/clusteradd/res.yaml
pkg/command/cluster/clusterlist/cmd_integration_api_test.go
pkg/command/cluster/clusterupdate/cmd.go
pkg/command/cluster/clusterupdate/res.yaml
vendor/github.com/scylladb/scylla-manager/v3/pkg/managerclient/client.go
vendor/github.com/scylladb/scylla-manager/v3/pkg/managerclient/model.go
vendor/modules.txt

This is the final PR regarding handling alternator creds. It contains some api tests, but I also made a manual validation in order to make sure that everything works and looks as expected:
```
miles@fedora:~/scylla-manager$ ./sctool.dev cluster add --host 192.168.200.11 --auth-token token -u cassandra -p cassandra --name myc
965faf8d-5473-4198-b35a-6f6b6a2b4aa8
__  
/  \     Cluster added! You can set it as default, by exporting its name or ID as env variable:
@  @     $ export SCYLLA_MANAGER_CLUSTER=965faf8d-5473-4198-b35a-6f6b6a2b4aa8
|  |     $ export SCYLLA_MANAGER_CLUSTER=myc
|| |/    
|| ||    Now run:
|\_/|    $ sctool status -c myc
\___/    $ sctool tasks -c myc
miles@fedora:~/scylla-manager$ ./sctool.dev cluster list
╭──────────────────────────────────────┬──────┬────────┬──────── …
```

Add flags for handling alternator creds

---

pkg/restapi/backup.go
pkg/restapi/mock_backupservice_test.go
pkg/restapi/services.go
pkg/scyllaclient/client_agent.go
pkg/service/backup/purger.go
pkg/service/backup/schema.go
pkg/service/backup/schema_test.go
pkg/service/backup/service.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/backup/stage.go
pkg/service/backup/worker.go
pkg/service/backup/worker_alternator.go
pkg/service/backup/worker_schema.go
pkg/testutils/db/db.go

This PR extends backup procedure with alternator schema.
It also extends GetDescribeSchema to GetSchema which also returns alternator schema and it's used for testing alternator schema completion. The real backup restore tests will be performed when alternator restore is implemented.
Fixes #4512

Alternator backup

---

pkg/ping/dynamoping/dynamoping_integration_test.go
pkg/service/cluster/service_integration_test.go
pkg/service/healthcheck/service_integration_test.go
pkg/testutils/exec.go
testing/Makefile
testing/scylla/config/scylla-ssl.yaml

This PR makes it so alternator setup respects `SSL_ENABLED` test env variable.
Fixes #4552

Setup alternator over TLS when SSL_ENABLED=true

---

pkg/sstable/sstable_naming.go
pkg/sstable/sstable_naming_test.go

Prepare for the addition of a new SSTable format version, `ms`, in an upcoming Scylla version.
Refs https://github.com/scylladb/scylladb/pull/26215

feat(sstable): add `ms` to the set of known SSTable format versions

---

pkg/scyllaclient/client_agent.go
pkg/service/backup/service_backup_integration_test.go
pkg/service/repair/service_repair_integration_test.go
pkg/service/restore/alternator.go
pkg/service/restore/restore_integration_test.go
pkg/service/restore/service_restore_integration_test.go
pkg/service/restore/worker.go
pkg/service/restore/worker_views.go
pkg/testutils/db/db.go
pkg/testutils/testhelper/helper.go

In scylla 2024.1 creating GSIs on existing table is not possible.
Because of that, we need to implement the same workaround as for
restoring LSIs, so just don't interact with them during data restoration.
The test for alternator backup/restore was mistakenly skipped because of
the assumption that if we can't back up alternator schema in a form of schema file,
then we can't restore it. That's not true for scylla 2024.1 where we can safely back up and restore
alternator schema from sstables, but we should still properly use alternator
api for handling other things (e.g. dropping and recreating views).

Fix alternator backup/restore for scylla 2024.1
